### ISSUE TITLE
NullArgumentException in AzureFileSystem.FixPath

### ISSUE THREAD

**Issue by jasonshsoftware** [JimBobSquarePants/UmbracoFileSystemProviders.Azure#101]
In FixPath, there is a line:
`if (path.StartsWith(appVirtualPath))`

This value is pulled from 
`public string ApplicationVirtualPath { get; internal set; } = HttpRuntime.AppDomainAppVirtualPath;`

I'm running chauffeur to build up my database and it fails to insert media because HttpRuntime.AppDomainAppVirtualPath is null, since it runs outside IIS. I've noticed elsewhere in this class when appVirtualPath is used, it has a nullability check. It should be added here as well.

**Comment by Jeavon** [comment]
@jasonshsoftware do you have an example of where it's already null checked? There are a few areas where HttpRuntime is used, they should probably all be null checked

**Comment by Jeavon** [comment]
I don't see any harm in adding this though:

            string appVirtualPath = this.ApplicationVirtualPath;
            if (appVirtualPath != null && path.StartsWith(appVirtualPath))
            {
                path = path.Substring(appVirtualPath.Length);
            }

**Comment by jasonshsoftware** [comment]
`
private string ResolveUrl(string path, bool relative)
        {
            // First create the full url
            string fixedPath = this.FixPath(path);

            Uri url = new Uri(new Uri(this.rootContainerUrl, UriKind.Absolute), fixedPath);

            if (!relative)
            {
                return url.AbsoluteUri;
            }

            if (this.UseDefaultRoute)
            {
                return $"{this.ApplicationVirtualPath?.TrimEnd('/')}/{Constants.DefaultMediaRoute}/{fixedPath}";
            }

            return $"{this.ApplicationVirtualPath?.TrimEnd('/')}/{this.ContainerName}/{fixedPath}";
        }
`

This uses the ?. null continuation.

**Comment by Jeavon** [comment]
If you want to try out the pre-release it now contains the null check
