### ISSUE TITLE
Cannot delete (remove) or replace an image cropper image with 1.0.1

### ISSUE THREAD

**Issue by t9creative** [JimBobSquarePants/UmbracoFileSystemProviders.Azure#102]
Hello.  With the latest 1.0.1 installation of this package, I cannot delete or replace an image that is saved in the image cropper. (actually saving or publishing after removing/replacing)  I get the following error in my log:

`System.IO.DirectoryNotFoundException: Blob not found at '\media\1030'
 2018-01-15 10:37:31,318 [P244376/D2/T179] ERROR Umbraco.Web.Editors.ContentController - Unhandled controller exception occurred
System.ArgumentNullException: Value cannot be null.
Parameter name: source`

If I go back to 1.0.0 of the package, I can successfully delete or replace.

**Comment by JimBobSquarePants** [comment]
@Jeavon That must relate to the changes made here.
 https://github.com/JimBobSquarePants/UmbracoFileSystemProviders.Azure/commit/cb54a23b64756d380fdb08c24ee2e4bac12f729f

I'm in no position to dogfood this at the moment so will have to leave it to you.

**Comment by Jeavon** [comment]
I'm looking into it, strange unit tests didn't pick it up

**Comment by Jeavon** [comment]
I have pushed a temp fix for this (I'm testing it) however I think it's uncovered a deeper issue when useDefaultRoute is enabled and the containerName is not "media". 

The path parameter of GetFiles appears to always contain the "media" path, e.g. "media/1000/blaa.jpg" however this isn't correct as the blob path is "mycontainer/1000/blaa.jpg", hence why the change to https://github.com/JimBobSquarePants/UmbracoFileSystemProviders.Azure/commit/cb54a23b64756d380fdb08c24ee2e4bac12f729f has triggered this. So the change is correct itself....

**Comment by Jeavon** [comment]
Ok, so I think I've tracked down the true issue for this and fixed it here https://github.com/JimBobSquarePants/UmbracoFileSystemProviders.Azure/commit/86b381c08def86a09fdac4f5b646795903d3de32

The path coming into the GetFiles is in the format "\\media\\1005" but currently the "\\" were removed only at the end missing out on all the logic beforehand which is required!

All tests are passing but I love a review on this @JimBobSquarePants

**Comment by JimBobSquarePants** [comment]
Other than the old duplicate allocation that makes sense to me. 👍

**Comment by Jeavon** [comment]
Cool, I'm going test on a couple of projects and then release all being well.

**Comment by Jeavon** [comment]
This web goes even deeper! If you create a media item and then save it, thumbnail images are created in the blob folder and when you delete the item the thumbnail images are left behind (as is the folder of course) however if you create the image via drag and drop the thumbnails are not created so when you delete the folder doesn't exist. Therefore to support both scenario I'm going back to returning Enumerable.Empty instead of null. I'm sure there's something wrong in Umbraco with regard to creation/deletion of these thumbs too but that's a different issue.

**Comment by JimBobSquarePants** [comment]
It would be really nice if Umbraco actually used their own API's properly. As far as I recall there's not even any unit tests for the default implementation. 🙁

**Comment by Jeavon** [comment]
Yup, v8 will have so many more tests and be so much more testable, the joy of killing legacy.

I'm going to release this as v1.0.2 as it's pretty critical but please @t9creative let me know how you find it
