### ISSUE TITLE
Images are showing from Umbraco Backend but not in my pages

### ISSUE THREAD

**Issue by jayantrajwani** [JimBobSquarePants/UmbracoFileSystemProviders.Azure#103]
I am working on an existing umbraco project. It is not allowing me to upload any files to media. Though it is showing me the images in media on backend but it is not loading them on the site.
![img2 umb](https://user-images.githubusercontent.com/11351528/35215123-5b1d6924-ff89-11e7-922f-ec1ecd4f88ca.png)
![img1 umb](https://user-images.githubusercontent.com/11351528/35215124-5b4d380c-ff89-11e7-848d-20944ecf0500.png)

Any help would be greatly appreciated. Thanks!

**Comment by jayantrajwani** [comment]
Yes! Also i tried installing The filesystemprovider.azure package from nuget but it lead me to countless errors.

**Comment by JimBobSquarePants** [comment]
@jayantrajwani Ok thanks,

Looking at your error message on the right hand side in the second image you are clearly missing the filesystem binaries in your bin folder. 

I would uninstall the plugin, run a clean build of your solution and reinstall the plugin with the correct config you should be ok.

**Comment by jayantrajwani** [comment]
Doing that it gives me some errors with htmlagilitypack. Fixing which gives me some other error looking for solution to it, People are asking to update from mvc 4 to mvc 5

**Comment by jayantrajwani** [comment]
@JimBobSquarePants I had been trying to install it from nuget package manager from visual studio. Apparently after trying for 1 week the solution was as simple as installing the same package from umbraco backend.
Thanks for the help. :)

**Comment by JimBobSquarePants** [comment]
@jayantrajwani 

No worries,

Nuget is the preferred option and works well. I think you have something wrong with your solution configuration.

**Comment by jayantrajwani** [comment]
I too feel the same. Because once i stopped the project it's not working again.
