### ISSUE TITLE
CloudImageService with private storage

### ISSUE THREAD

**Issue by tobbbe** [JimBobSquarePants/UmbracoFileSystemProviders.Azure#111]
Hello!

Is it possible to use CloudImageService with private storage yet? I know the Readme says
`The CloudImageServiceis not compatible with the FileSystemProvider when using private storage. You will have to build your own IImageService implementatio`
but Im hoping it maybe has changed or anyone has made a working IImageService  😄 

Im trying to serve protected umbraco media files for a closed intranet.

Any help is appreciated!

**Comment by JimBobSquarePants** [comment]
Hi there,

The `CloudImageService` is part of the [ImageProcessor](https://github.com/JimBobSquarePants/ImageProcessor) library not UmbracoFileSystemProviders.Azure.

I would have a look at the code in that project for guidance.

Cheers

James
