### ISSUE TITLE
Migrate images from Azure to own server

### ISSUE THREAD

**Issue by villian** [JimBobSquarePants/UmbracoFileSystemProviders.Azure#114]
Is it possible to migrate Umbraco media section that worked with Azure for a while to server disk? Is there some technique?

**Comment by jesperordrup** [comment]
To follow up on Alex/Villian 

We have removed the provider.
We have downloaded all media from Azure and copied it to the media folder.

But .. Umbraco "starts" over with numbering the folders?`

**Comment by JimBobSquarePants** [comment]
I would raise this on the Umbraco issues tracker not here. We don't generate the folder numbers, the provider merely handles communication with blob storage.

**Comment by jesperordrup** [comment]
Thx. And you're right and it's solved.

We had to refresh indexes AND restart app then it started behaving correct.

**Comment by JimBobSquarePants** [comment]
Ah yes, It's all tied to Examine isn't it!
