### ISSUE TITLE
Migration?

### ISSUE THREAD

**Issue by JohnBergman** [JimBobSquarePants/UmbracoFileSystemProviders.Azure#117]
Anyone have any processes documented as far as how to move an existing site to using the new provider; I have about 20,000 images and videos I'd like to migrate into using this...

**Comment by JimBobSquarePants** [comment]
Hi @JohnBergman ,

It should be as simple as the following.

- Download [Azure Storage Explorer](https://azure.microsoft.com/en-gb/features/storage-explorer/) and use that to copy the media folder structure to you new blob storage.
- Install and configure our provider.
- Rebuild the Examine indexes

Cheers

James
