### ISSUE TITLE
What's the difference between AzureBlogFileSystem and AzureFileSystem?

### ISSUE THREAD

**Issue by bhaidar** [JimBobSquarePants/UmbracoFileSystemProviders.Azure#121]
Hello,
I am reading through the code and noticed two implementations of IFileSystem. The AzureBlogFileSystem and AzureFileSystem.

What's the difference between those two?

Thanks
Bilal

**Comment by JimBobSquarePants** [comment]
You mean `AzureBlobFileSystem` not `AzureBlogFileSystem`? 

One handles parsing and setup of the Umbraco configuration and the other handles the actual `IFileSystem` implementation. I'm sure it could be simplified somewhat now but I don't want to invest the time to do so as it works. 

Cheers

James
