### ISSUE TITLE
User Avatar image does not work when using Azure for storage

### ISSUE THREAD

**Issue by t9creative** [JimBobSquarePants/UmbracoFileSystemProviders.Azure#131]
If you go to edit a profile of a user (backoffice user) and attempt to upload an image to use for the picture/avatar, it does not work.

It's attempting to host the file at /media/UserAvatars

**Comment by JimBobSquarePants** [comment]
>It does not work

What doesn’t? A little detail goes a long way. Version numbers, error messages etc please. 

If all other images work then logic would dictate it’s an umbraco bug. They’ve been guilty of not using their own APIs in the past.

**Comment by coderpros** [comment]
Actually, I'm having exactly the same issue on 7.15.6 of Umbraco using version 1.1.1 of UmbracoFileStorage.Azure. Obviously, as I'm still on v7 (waiting for the core version of Umbraco before I upgrade) I can't upgrade to v2 of UmbracoFileStorage.Azure. Everything else that was saved in my media folder works fine, but UserAvatars return a 404.
