### ISSUE TITLE
ImageProcessor only working on local dev

### ISSUE THREAD

**Issue by toporan** [JimBobSquarePants/UmbracoFileSystemProviders.Azure#134]
Installed the latest version using nuget and did all the settings. Everything's fine, except the ImageProcessor does not work anymore on the production server. 
img.png?width=xx etc. has no effect on the images. They work fine on my localhost dev.
Am I missing something?
Thanks

**Comment by JimBobSquarePants** [comment]
> Am I missing something?

You must be. Check your configuration, whether you are deploying binaries correctly etc and try again. You may still have the old dlls in your production environment.
