### ISSUE TITLE
Are there plans for an Umbraco v8 version?

### ISSUE THREAD

**Issue by JoseMarcenaro** [JimBobSquarePants/UmbracoFileSystemProviders.Azure#137]
Hi @JimBobSquarePants - this package is great.
Are you planning to implement an Umbraco 8 version?
Thanks!

**Comment by dklinzing** [comment]
Seems like there is a branch for it: https://github.com/JimBobSquarePants/UmbracoFileSystemProviders.Azure/tree/develop-umbraco-version-8.  Not sure of the status, though.

**Comment by JoseMarcenaro** [comment]
Thanks a lot Daniel for the heads up!  I'll look into it. 😃

**Comment by JoseMarcenaro** [comment]
With the latest commit from @Jeavon an hour ago, the Umbraco v8 version actually works! yay!
(you still need to manually add the required configuration settings).  Thanks!

**Comment by Jeavon** [comment]
I have changed a fair bit in the last few days. I believe that both the NuGet and Umbraco packages are now working. I'm planning on making an alpha release next week.
Umbraco package - https://ci.appveyor.com/project/JamesSouth/umbracofilesystemproviders-azure/builds/23621914/artifacts (zip)
NuGet package - https://www.myget.org/feed/umbraco-packages/package/nuget/UmbracoFileSystemProviders.Azure

**Comment by Jeavon** [comment]
I have released v2.0.0-alpha1 for Umbraco v8
