### ISSUE TITLE
Container default access level possible security issue for Umbraco Forms

### ISSUE THREAD

**Issue by AstuteMediaDev** [JimBobSquarePants/UmbracoFileSystemProviders.Azure#138]
Related to #67 and #98

> there is a hard-coded use of BlobContainerPublicAccessType.Blob when creating the container.

Umbraco Forms uploads files to /media/forms and we only just realised the default container access is public so anyone could potentially access sensitive user uploads if they were aware of the storage account url.

**Comment by JimBobSquarePants** [comment]
We have other options now. It's not hard coded since #64 

It's also documented.

https://github.com/JimBobSquarePants/UmbracoFileSystemProviders.Azure#usage

Protecting the media by default changes the default behaviour from the file based service and requires ImageProcessor.Web customization.

**Comment by AstuteMediaDev** [comment]
Sorry @JimBobSquarePants can we just confirm something which isn't clear in the documentation.

Are you saying we cannot use the standard ImageProcessor.Web file system storage if we set the Azure media container to private? 

Image Processor has stopped working for us and we're trying to determine the cause.
