### ISSUE TITLE
404 returned by Azure Storage returns a 500 in Umbraco

### ISSUE THREAD

**Issue by Swimburger** [JimBobSquarePants/UmbracoFileSystemProviders.Azure#139]
When an image is requested that no longer exists in Azure Storage, Azure Storage will return an HTTP status code 404 to Umbraco.
Umbraco as a result will return an HTTP status code 500.
I believe it would be more appropriate if Umbraco also returned a 404.

At least 404 would be the right HTTP status code in my specific use case, because I want whoever is requesting this image to know it doesn't exist anymore.
Can I change this behavior myself?

**Comment by JimBobSquarePants** [comment]
Stack trace? We don't know whether the bug is in Umbraco or here without one and couldn't possibly comment.

**Comment by Swimburger** [comment]
Nvm, it's because of the `customErrors` configuration that redirect the 404 exception to the 500.aspx page.
When custom errors is turned off, 404 is properly returned. Sorry for false alarm.

**Comment by JimBobSquarePants** [comment]
Ah brilliant. Thanks for letting us know 👍
