### ISSUE TITLE
Transaction was deadlocked on lock -  Media Event Handler

### ISSUE THREAD

**Issue by akeilox** [JimBobSquarePants/UmbracoFileSystemProviders.Azure#14]
I am experimenting with the mediaservice event handler, to automate uploading of media by semi-automated means - and eventually find the best path to gradually move media to azure.

I have started reading https://our.umbraco.org/documentation/reference/events/mediaservice-events then looked at sample code and proceed with a basic test case.

In my basic experimentation with media service event handler, i tried to attach to media saved event and copy saved media to another drive (aka simple test case).

The code

 

    protected override void ApplicationStarted(UmbracoApplicationBase umbracoApplication, ApplicationContext applicationContext)
            {
                MediaService.Saved += MediaServiceSaved;     
            }   
    
            void MediaServiceSaved(IMediaService sender, SaveEventArgs<IMedia> e)
            {
    		
                foreach (var mediaItem in e.SavedEntities)
                {
                     var umbracoFileProperty = mediaItem.Properties["umbracoFile"].Value.ToString(); 
    
     var newfile = .. get file path and server.mappath it
    var fromPath = get target copy directory mappath
    
    	var fi = new System.IO.FileInfo(newfile);
    
                if (!fi.Directory.Exists) fi.Directory.Create();	
    			System.IO.File.Copy(fromPath,newfile);
            }
    }

When i save a single and/or multiple files from Media Section-> Upload, the file copy (backup) takes place fine but the UI throws error like

<pre>
Transaction (Process ID 54) was deadlocked on lock | communication buffer resources with another process and has been chosen as the deadlock victim. Rerun the transaction.
</pre>

This is on and off, it doesnt throw the error at once, but it does in second and consecutive tries.
The media gets saved just fine, so the event takes place(all within the same host so it occurs within a second or two), as well as copy. But the exception is shown to the end user, which ruins the test case.

Any idea why this is happening? Do I need to call some method before and/or after file copy to prevent this? 

Would greatly appreciate if someone can shed some light on this.

**Comment by akeilox** [comment]
kindly close this, as I believe its not related to UmbracoFileSystemProviders.Azure

**Comment by JimBobSquarePants** [comment]
Ok will do, thanks.
