### ISSUE TITLE
Change the MaxDays parameter to MaxMinutes or....?

### ISSUE THREAD

**Issue by Jeavon** [JimBobSquarePants/UmbracoFileSystemProviders.Azure#15]
If you want to deliver media through CDN, you most likely would want to set the CacheControl to 15 minutes or less as if you update a file with the same path the CDN will not refresh until the time has elapsed...?

A possible alternative approach would be to have a media save event which changed files names to guid's or appended a timestamp to existing filenames to cache bust it.

Interested to hear any other ideas...?

**Comment by JimBobSquarePants** [comment]
Hmmm... Hadn't thought of this. Pretty much always forget everything other than imageprocessor processed items.

I'd rather naming via timestamp if possible.

**Comment by Jeavon** [comment]
Yeah, it would be only for non-images such as PDF's I'm thinking timestamp filenames or guid's is the way to go
