### ISSUE TITLE
How to co-exist with other Media OnSave event handlers

### ISSUE THREAD

**Issue by akeilox** [JimBobSquarePants/UmbracoFileSystemProviders.Azure#17]
For compliance reasons, on one installation I have a Media Onsave event handler attached which is copying the /media/[id]/fileuploaded.jpg to a mapped drive S:  (i.e. taking a backup of uploaded media)

My question is, using the UmbracoFileSystemProviders.Azure side by side with the above, how can I take a copy to the S: drive when a media is uploaded;

my current code attach itself to MediaService.Saved event:

       protected override void ApplicationStarted(UmbracoApplicationBase umbracoApplication, ApplicationContext applicationContext)
        {
            MediaService.Saved    += MediaServiceSaved;     
         .......

     void MediaServiceSaved(IMediaService sender, SaveEventArgs<IMedia> e)
        {
		
		try{
            foreach (var mediaItem in e.SavedEntities)
            {

			 var umbracoFileProperty = mediaItem.Properties["umbracoFile"].Value.ToString();
             var mediaPath = System.Web.Hosting.HostingEnvironment.MapPath(umbracoFileProperty);
			 
			 var newPathFile = System.IO.Path.Combine(StoreFolder, umbracoFileProperty.Replace('/','\\'));

                         ... do System.File.IO.Copy (fromexisting, to newpath)

would be interested to hear your feedback on what modifications needed to get a copy of media file onSave and let it co-exist with Azure provider.

**Comment by Jeavon** [comment]
I think you would need to use the FileSystemProvider, I did something similar [here ](https://github.com/Jeavon/Umbraco-Crop-Healer/blob/master/Our.Umbraco.CropHealer/CropHealer.cs#L352)to get image dimensions
