### ISSUE TITLE
Single storage account with multiple containers

### ISSUE THREAD

**Issue by oohnajra** [JimBobSquarePants/UmbracoFileSystemProviders.Azure#18]
I really love this package! I have a question though. Would it be possible to use a single Azure storage account with a separate container for each project? In that case the container name would obviously be something like **media_projectname** or whatever and not **media**. I noticed in uHangout episode #74 (https://youtu.be/5Qp-ZGaKFaY?t=7m45s) that Jeavon mentioned “there could potentially be some issues” when using a container that isn't named **media**? Of course we'd still want the Virtual Path Provider to translate the URLs to /media/* for each individual project.

**Comment by JimBobSquarePants** [comment]
Thanks!

I need to have a bit of a play around with configuration and see what limitations there are to what Umbraco expects to be sure. I'll have an experiment and let you know what I come up with.

**Comment by oohnajra** [comment]
Awesome! Let me know what you find out.

**Comment by Jeavon** [comment]
I think this works ok actually, I have updated the Umbraco installer to support different containerName as it was not quite right before. I would love it if you tried it out, v0.5.1-beta-000068 or better :)

**Comment by oohnajra** [comment]
Awesome! I'm working on another project right now, but I'll test the new package as soon as I can, and I'll let you know how it works. Is there anything in particular you'd like me to test?

**Comment by Jeavon** [comment]
I should say it works for images only, requests for files that of course don't go through ImageProcessor do not directly. When you change the container name Umbraco will return the path to the file, e.g. my container name is "mediaMyProject" so the paths returned by Umbraco will be "/mediaMyProject/1011/myimage.jpg" the CloudSevice of ImageProcessor is happy to pick this up but if it's a PDF then it has to be requested from the media path e.g. "/media/1012/mypdf.pdf"

**Comment by Jeavon** [comment]
I think we need to adjust the pathPrefix parameter in this method https://github.com/JimBobSquarePants/UmbracoFileSystemProviders.Azure/blob/develop/src/UmbracoFileSystemProviders.Azure/FileSystemVirtualPathProvider.cs#L84 to read the prefix from FileSystemProviderManager

**Comment by JimBobSquarePants** [comment]
>"Resharper seems drunk."

Classic commenting on my part there... That's a method I've been wanting to tinker with for a while as it affects #5

**Comment by perosb** [comment]
Maybe the internal Umbraco path should be "media"? regardless of the containerName?

That would also make it easier to move a database across environments which use different containerNames.

**Comment by oohnajra** [comment]
>Maybe the internal Umbraco path should be "media"? regardless of the containerName?

>That would also make it easier to move a database across environments which use different containerNames.

I agree!

**Comment by oooshola** [comment]
Hey guys, has there been any solution to this? On the front end, things work find since I can always modify the <img> src to be prefixed with "media." However, if i upload an image to the media section, its backoffice thumbnail is a broken image, since the thumbnail points to "/media_projectname/2059/example.jpg?width=500&mode=max"

Thanks!

**Comment by Jeavon** [comment]
@oooshola Please try out the latest build v0.5.1-beta-000069 as I think I've fixed this so you shouldn't need your line in ApplicationStarting

**Comment by oooshola** [comment]
Yep @Jeavon this seems to do the trick. Thanks!

**Comment by Jeavon** [comment]
@oooshola great! I was thinking about seeing if I could get it to work keeping "media" as the virtual path but allowing a different container name, do you think it's worth exploring?

**Comment by JimBobSquarePants** [comment]
I would say yes to that if possible. It reduces the possibility of naming conflicts with virtual paths and filenames plus would make it consistent across different environments.

**Comment by oooshola** [comment]
@Jeavon I would definitely say that's something worth looking at!

**Comment by Jeavon** [comment]
I have tried to get it work so that in Umbraco the path remains "media" but your container name can be whatever you like but I've not yet had any success, I will create a feature to have another look at in the future.

**Comment by oooshola** [comment]
@Jeavon yeah, I imagine it wouldn't be very easy. Thanks again for looking into it.
