### ISSUE TITLE
SecurityException: An attempt to download a remote file has been halted because the file is larger than allowed

### ISSUE THREAD

**Issue by akeilox** [JimBobSquarePants/UmbracoFileSystemProviders.Azure#19]
I am getting blank/image not found on few media, when checked the blob for one
file size is 10.17M
and when requested direct in browser i get the following error.
Is the download/upload threshold something set as default and suggested, or must be changed from the azure interface?

<pre>
[SecurityException: An attempt to download a remote file has been halted because the file is larger than allowed.]
   ImageProcessor.Web.Helpers.<GetWebResponseAsync>d__0.MoveNext() +689
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +144
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +84
   ImageProcessor.Web.Services.<GetImage>d__2.MoveNext() +987
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +144
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +84
   System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() +49
   ImageProcessor.Web.HttpModules.<ProcessImageAsync>d__11.MoveNext() +3913
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +144
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +84
   System.Web.TaskAsyncHelper.EndTask(IAsyncResult ar) +98
   System.Web.AsyncEventExecutionStep.OnAsyncEventCompletion(IAsyncResult ar) +166
</pre>

**Comment by JimBobSquarePants** [comment]
Hi akeilox,

You've posted this on the wrong repo. The  stack trace doesn't mention this library at all and mentions **ImageProcessor.Web** only. It's pretty self explanatory. The file you are attempting to download is larger than allowed.

>SecurityException: An attempt to download a remote file has been halted because the file is larger than allowed.

This is a value that can be configured via the ImageProcessor configuration files. The configuration files are described in detail both on this repo.

https://github.com/JimBobSquarePants/UmbracoFileSystemProviders.Azure#combining-with-imageprocessor

and on the ImageProcessor documentation page 

http://imageprocessor.org/imageprocessor-web/configuration/#securityconfig

Up the `MaxBytes` value to the required amount and the exception will go away.

However... I would also try to ensure that the resources are not so huge. Resizing a 10MB image is an expensive operation and the server is not the best location for performing such operations.

**Comment by akeilox** [comment]
@JimBobSquarePants Apologies for posting this on the wrong section. I didnt have a proper grasp of the relation between UmbracoFileSystemProviders.Azure and ImageProcessor at the time and was tracing the issues occured after moving to UmbracoFileSystemProviders.Azure.
Didnt occur to me as I had maxrequestlenght and uploadlength set to high in web.config, and not knowing how ImageProcessor worked.

Appreciated you taking the time to clarify and point me in the right direction. ImageProcessor is gigantic with lots of config options and features. A great help.

I took your advise and let the 10MB image size restriction in place, and informed end users to downsize and re-upload the image below 10MB.

**Comment by JimBobSquarePants** [comment]
I'm glad you're getting to grips with it a bit better now. I appreciate that it is a complicated to follow everything at times, I struggle myself sometimes and I wrote it!

**Comment by bjarnef** [comment]
@JimBobSquarePants I know this one is old, but a project we have taken over we have many of these errors.

where both `CloudImageService` and `RemoteImageService` has:

```
<setting key="MaxBytes" value="50194304" />
```

Any chance to know which image is being requested? and I also wonder what `MyComputer` is, which seems odd.

![image](https://github.com/umbraco-community/UmbracoFileSystemProviders.Azure/assets/2919859/bdef8a46-9646-423c-81d5-be77acb8a0bb)
