### ISSUE TITLE
Accept-Ranges support

### ISSUE THREAD

**Issue by perosb** [JimBobSquarePants/UmbracoFileSystemProviders.Azure#20]
Current setup is using:
UmbracoFileSystemProviders.Azure
CloudImageService
AzureBlobCache
StreamCachedImage=true

So not quite sure where this goes but if you have video, .mp4, uploaded.
I assume this doesn't go through ImageProcessor, but still through the above.

The videos are not seekable and doesn't support "Accept-Ranges".

What are your thoughts on this?

The only solution I have found so far is to setup an additional sub domain pointing directly to the Storage container on azure.

**Comment by akeilox** [comment]
For my test setup (only UmbracoFileSystemProvider.Azure, havent get to AzureBlobCache yet as I wasnt sure about the cost of CDN for a small scale website);

the images are being served from the cache but the video and pdf etc. are fetched direct from the blob storage i believe as I see requests like;

5501         /media/93712/background-video.mp4
5435         /app_data/cache/2/d/8/a/7/1/2d8a71c88ae38793df855f76002567f0bbbc9804.gif

Within the context of UmbracoFileSystemProvider.Azure, is there a way to edit code/config to let it cache the pdf and mp4 files to app-data/Temp/cache too?
Having files stored in Azure blob is great, but I dont know the cost of I/O for each .mp4 or .pdf being hit to azure blob storage.

In this case, for a small site that is serving primarily one country, adding CDN seems to add extra costs.
Being new to Azure and all, I am not sure if the CDN costs will justify the Azure Blob I/O (transfer out) in the long run.

A bit of penny pinching, you may think, but it does make me wonder what to expect and justify it.

If all media is cached locally, in the temp, than that would be great to mimize the traffice, I/O costs in Azure.

**Comment by perosb** [comment]
@akeilox not sure what that has to do with Accept-Ranges support.

**Comment by akeilox** [comment]
@perosb its definitely not relatd to Accept-Ranges, I saw your post at the same time when I was looking at the traffic of cache to understand more and how the mp4 or other files can be cached.
Might be off-topic, will put in in a new question.

**Comment by JasonElkin** [comment]
Ran into this same problem yesterday, it breaks MP4 playback on Safari. I fixed it by serving the video directly from blob storage/CDN (which we intended to implement anyway).

In an ideal world an IFileSystem should indeed be able to do this (Accept Ranges etc.), however...

It's not very efficient for our sites to act as a middleman, using extra bandwidth/CPU cycles/HTTP connections. If we're using Azure Blob Storage we're already paying for an out-of-band web endpoint for our files, it makes sense to use that to serve the files.

@akeilox the outbound data transfer rates are actually the same for transfers out of the CDN as they are for transfers out of Web Apps VMs etc. The only extra you _should_ end up paying is the transfer from your Web App/VM/Blobs to the CDN itself.

**Comment by JimBobSquarePants** [comment]
I'd actually forgotten about this issue. A new one #61 was actually raised the other day which duplicates it. We have some code samples which could allow us to add this functionality in that issue but I have no means to test what I am doing since I do not have a blob storage account just now. 

@JasonElkin is this something you would be able to have a look at?

**Comment by JasonElkin** [comment]
I'll take a look - In principle it should be similar to my PR on ImageProcessor - just a case of mapping headers across. I could have a look at implementing 304s at the same time.

**Comment by JimBobSquarePants** [comment]
That's why I thought you'd be good to look at it, you know what you're doing. Cheers! 😄

**Comment by JimBobSquarePants** [comment]
Hey @JasonElkin Did you ever get the chance to look at this?

**Comment by JasonElkin** [comment]
@JimBobSquarePants have had a look, but not had a chance to code & test yet. Am working on integrating this with a project in the next couple of weeks so should have a PR ready then.

**Comment by JimBobSquarePants** [comment]
@JasonElkin Thanks! I think this is one of the final pieces of the puzzle.

**Comment by Jeavon** [comment]
Fixed in v0.5.9

**Comment by rangler2** [comment]
> @perosb its definitely not relatd to Accept-Ranges, I saw your post at the same time when I was looking at the traffic of cache to understand more and how the mp4 or other files can be cached. Might be off-topic, will put in in a new question.

Sorry to comment on old issue but did you ever find a way to cache all media files to local disk @akeilox ?
Have similar requirement on a private (ip restricted) Umbraco v7 instance moving to Azure so using blob storage but want that to be Private however some large files (e.g. 20mb mp4) are extremely slow to load via /media url using the virtual path provider. Ideally want to have them cached on disk on 1st load just like image-processor resized images are. Thanks

**Comment by c9mb** [comment]
@rangler2 - You perhaps should be loading from Blob-Storage via Azure-CDN and using CORS to manage access if required. Also, for Umbraco-7 it may be worth taking a look at the AzureCDNToolkit - it allows direct access to the cached processed location, to avoid the 301/2 redirects, but at the cost of initialization time if you have lots of files - although that can be negated using REDIS.
