### ISSUE TITLE
Version 3 does appear to work with Forms 8.8

### ISSUE THREAD

**Issue by NikRimington** [JimBobSquarePants/UmbracoFileSystemProviders.Azure#200]
Hi,

I upgraded to version 3 of this package (with the forms add on) and it resulted in Forms breaking. The logs filled up with the following error: `blob not found at 'forms/forms'` even though the web.config setup was using `forms-dev` as the blob container name.

Site is running Umbraco 8.16.0, Umbraco Forms 8.8.0.

Site started on Umbraco 8.7.0, and Umbraco Forms. 8.5.3 so has upgraded through the various versions to get to the ones mentioned above.

I confirmed that the forms config was set with StoreFormsInDB as false.

Rolling back to v2.0.1 resulted in the forms coming back to life.

I couldn't find any obvious additional details that could point to the cause of the problem, but wanted to log the issue here incase anyone else comes across it.

Thanks,

Nik

**Comment by Jeavon** [comment]
I have released v3.0.1 with a fix for this issue! Thanks
