### ISSUE TITLE
Caching of non image media

### ISSUE THREAD

**Issue by akeilox** [JimBobSquarePants/UmbracoFileSystemProviders.Azure#21]
For my test setup (only UmbracoFileSystemProvider.Azure, havent get to AzureBlobCache yet as I wasnt sure about the cost of CDN for a small scale website);

the images are being served from the cache but the video and pdf etc. are fetched direct from the blob storage i believe as I see requests like;

5501 /media/93712/background-video.mp4
5435 /app_data/cache/2/d/8/a/7/1/2d8a71c88ae38793df855f76002567f0bbbc9804.gif

Within the context of UmbracoFileSystemProvider.Azure, is there a way to edit code/config to let it cache the pdf and mp4 files to app-data/Temp/cache too?
Having files stored in Azure blob is great, but I dont know the cost of I/O for each .mp4 or .pdf being hit to azure blob storage.

In this case, for a small site that is serving primarily one country, adding CDN seems to add extra costs.
Being new to Azure and all, I am not sure if the CDN costs will justify the Azure Blob I/O (transfer out) in the long run.

A bit of penny pinching, you may think, but it does make me wonder what to expect and justify it.

If all media is cached locally, in the temp, than that would be great to mimize the traffice, I/O costs in Azure. The site hosted in client premises.

**Comment by JimBobSquarePants** [comment]
You're mixing up two separate libraries here. 

ImageProcessor caches processed image requests when using the diskcache. That is why you are seeing results pulled from there. We can't mix them as there are completely unaware of each other and it could cause issues when trying to clean up. 

We are already caching in-browser to reduce I/O costs anyway. 

https://github.com/JimBobSquarePants/UmbracoFileSystemProviders.Azure/blob/develop/src/UmbracoFileSystemProviders.Azure/FileSystemVirtualFile.cs#L81
