### ISSUE TITLE
Azure blob storage retries

### ISSUE THREAD

**Issue by mokonta** [JimBobSquarePants/UmbracoFileSystemProviders.Azure#22]
I was wondering whether this package implements a retry policy when trying to access a blob. It needs this to circumvent periodical transient Azure connection errors. If it's not already implemented, is this something that is feasible to do?

**Comment by Jeavon** [comment]
As we are using the Azure Storage Client v4, a retry policy is built into the client/SDK. There is more info available here https://azure.microsoft.com/en-gb/documentation/articles/best-practices-retry-service-specific/#azure-storage-retry-guidelines

**Comment by JimBobSquarePants** [comment]
:+1: On finding the docs. Very useful.

**Comment by Jeavon** [comment]
The default configuration that is in place from the client should be sufficient, so I I think we can close this issue?

**Comment by JimBobSquarePants** [comment]
Agreed. @mokonta You satisfied by that?

**Comment by mokonta** [comment]
Very satisfied. Thanks guys.
