### ISSUE TITLE
Azure Blob Cache

### ISSUE THREAD

**Issue by troyfulton** [JimBobSquarePants/UmbracoFileSystemProviders.Azure#24]
Hello, i'm trying to use the Azure Blob Cache.  I have everything setup, but it's returning 404.  And it's shaping the image and storing it in the blob.

http://cornerstone.kyamedia.com/cornerstone/media/AllFiles/1X1/1x1-redheart-MD.jpg?width=1000&height=300&mode=crop&format=jpg&scale=both

Here is my security config:

    <service name="LocalFileImageService" type="ImageProcessor.Web.Services.LocalFileImageService, ImageProcessor.Web" /> 
    
    <service name="CloudImageService" type="ImageProcessor.Web.Services.CloudImageService, ImageProcessor.Web">
      <settings>
        <setting key="Container" value="cache"/>
        <setting key="MaxBytes" value="8194304"/>
        <setting key="Timeout" value="30000"/>
        <setting key="Host" value="https://xxxx.blob.core.windows.net/"/>
      </settings>
    </service>

My Cache Config

	<caching currentCache="AzureBlobCache">
	  <caches>
		<cache name="DiskCache" type="ImageProcessor.Web.Caching.DiskCache, ImageProcessor.Web" maxDays="365">
		  <settings>
			<setting key="VirtualCachePath" value="~/app_data/cache" />
		  </settings>
		</cache>
	  <cache name="AzureBlobCache" type="ImageProcessor.Web.Plugins.AzureBlobCache.AzureBlobCache, ImageProcessor.Web.Plugins.AzureBlobCache" maxDays="365">
		  <settings>
			<setting key="CachedStorageAccount" value="DefaultEndpointsProtocol=https;AccountName=;AccountKey=" />
			<setting key="CachedBlobContainer" value="cache" />
			<setting key="CachedCDNRoot" value="http://xxxx.azureedge.net/" />
			<setting key="SourceStorageAccount" value="" />
			<setting key="SourceBlobContainer" value="" />
			<setting key="StreamCachedImage" value="false" />
		  </settings>
		</cache>
	  </caches>
	</caching>

**Comment by Jeavon** [comment]
@troyfulton You will need to use build 69 for this to work. Are you using Umbraco or NuGet packages?

**Comment by JimBobSquarePants** [comment]
Hi @troyfulton 

Your security config is incorrect. You're missing values that are specified in the readme on this repo.

``` xml
<?xml version="1.0"?>
<security>
  <services>
    <service name="LocalFileImageService" type="ImageProcessor.Web.Services.LocalFileImageService, ImageProcessor.Web"/>
    <service prefix="media/" name="CloudImageService" type="ImageProcessor.Web.Services.CloudImageService, ImageProcessor.Web">
      <settings>
        <setting key="MaxBytes" value="8194304"/>
        <setting key="Timeout" value="30000"/>
        <setting key="Host" value="http://[myAccountName].blob.core.windows.net/media/"/>
      </settings>
    </service>
  </services>  
</security>
```

Your `CloudImageService` is missing the `media/` prefix and the `Host` setting does not end in `/media/`

I can never remember whether the `Host` setting should end in `cornerstone/media/` (For shame!) I always just use the default settings. How come it's under that url anyway? http://cornerstone.kyamedia.com/cornerstone/ gives a 404. I would expect that to be a landing page or something?

Out of curiosity what does the `scale=both` parameter do? I can't remember writing a processor for ImageProcessor.Web that recognises that parameter.

**Comment by troyfulton** [comment]
Hello, I'm using nuget.  Thank you.

Troy Fulton / Director of Research and Development
cell: 303.378.5040<tel:303.378.5040>/ troy.fulton@kyamedia.com<mailto:troy.fulton@kyamedia.com>

KYA Media
Office: 303.997.3230 x700<tel:303.997.3230;700>
4833 Front Street. B207
Castle Rock, CO 80104
http://www.kyamedia.com




On Tue, Feb 2, 2016 at 2:11 AM -0800, "Jeavon" <notifications@github.com<mailto:notifications@github.com>> wrote:


@troyfulton<https://github.com/troyfulton> You will need to use build 69 for this to work. Are you using Umbraco or NuGet packages?

-

**Comment by troyfulton** [comment]
So, I’ve been evaluating your tool and ImageResizer…and I think scale=both is left over from that.  It basically fits the image in to the height & width after the other processes happen.

Ok, so my blob container is called “cache"  so would my prefix be "cache/“ or still “media/“?

Also, my host probably should be https://kyaimages.blob.core.windows.net/cache/ which is the path to my azure storage blob container…with a container name “cache”

So now with my configs as follows, I get the image back, but it’s not getting stored in the blog…and it’s not being processed.
http://cornerstone.kyamedia.com/cornerstone/media/AllFiles/1X1/1x1-africa-MD.jpg?width=1000&heigth=300&mode=crop&format=jpg


<?xml version="1.0" encoding="utf-8"?>
<security>
  <services>
    
    
    <service prefix="media/" name="CloudImageService" type="ImageProcessor.Web.Services.CloudImageService, ImageProcessor.Web">
      <settings>
        
        <setting key="MaxBytes" value="8194304"/>
        <setting key="Timeout" value="30000"/>
        <setting key="Host" value="https://kyaimages.blob.core.windows.net/cache/"/>
      </settings>
    </service>
    <service prefix="remote.axd" name="RemoteImageService" type="ImageProcessor.Web.Services.RemoteImageService, ImageProcessor.Web">
      <settings>
        <setting key="MaxBytes" value="4194304" />
        <setting key="Timeout" value="3000" />
        <setting key="Protocol" value="http" />
      </settings>
      <whitelist>
      </whitelist>
    </service>
  </services>
</security>

**Comment by JimBobSquarePants** [comment]
Hi Troy, I attempted to reformat your question above to make it more readable but Github seems to baulk on email replies.

Your settings for the CloudImageService should be as follows:

  ```xml
<?xml version="1.0" encoding="utf-8"?>
<security>
    <services>
        <service prefix="media/" name="CloudImageService" type="ImageProcessor.Web.Services.CloudImageService, ImageProcessor.Web">
        <settings>
            <setting key="MaxBytes" value="8194304"/>
            <setting key="Timeout" value="30000"/>
            <setting key="Host" value="https://kyaimages.blob.core.windows.net/media/"/>
        </settings>
        </service>
    </services>
</security>
  ```

An explanation:

Both ImageProcessor`s AzureBlobCache and this library will automatically create blob containers.

- ImageProcessor will create one called `cache` where it will store processed images.
- UmbracoFileSystemProviders.Azure will create one called `media` where it will store any items uploaded to the media section in Umbraco.

When image are uploaded to the media section in the Umbraco backoffice using the provider the path is stored by Umbraco with a relative url by default using the power of the virtual path provider.

These usually follow the format:

    /media/1234/myimage.jpg?width=300

I can see that this varies quite dramatically from your url format. Are you using the media section or adding the files to that folder manually?

ImageProcessor will assign the CloudImageService to the image as it will recognise that the url is a valid image requests that begins with the `media\` prefix specified in the config. (the leading slash is stripped off while processing.) The service will combine the url with the `Host` value specified in the config to produce the full url

    https://kyaimages.blob.core.windows.net/media/1234/myimage.jpg?width=300

**Comment by troyfulton** [comment]
Ok, so, I’ll provide a bit more clarity on my end.


  *   I’m not using Umbraco…I’m using Kentico, a different CMS, but for our conversation, just assume I’m using a custom ASP.NET/C# application.
  *   I’m uploading images locally into folders under the state root…so it’s something like this:  http://www.kyamedia.com/images/someimage.jpg
     *   When I use DiskCache, and I process the above image, your code saves the processed image into the disk cache folder as a smaller processed image which is great.
  *   My plan was to use the CloudImageService to replace DiskCache in this scenario.  It’s a way to save the smaller processed images in Azure and serve them up via CDN
     *   We are not uploading images to Azure at all…I thought the CloudImageService would do it as described above.

So perhaps I’m misunderstanding the use and function of CloudImageService?

**Comment by JimBobSquarePants** [comment]
Hold on..... Then why is this conversation going on here? This is an issue tracker for an Umbraco specific library!

The ImageProcessor CloudImageService is designed for fetching images from a remote location when you are using a relative path. I describe what `IImageService` implementation are for in the ImageProcessor docs. http://imageprocessor.org/imageprocessor-web/extending/#iimageservice 

Since you are storing your files locally you do not want to be using it. the default LocalFileImageService will retrieve your images from your media folder and the AzureBlobCache will cache the processed result and perform a 302 to that result.

**Comment by troyfulton** [comment]
Sorry about the wrong forum…I was trying to use the plugin described here.  https://www.nuget.org/packages/ImageProcessor.Web.Plugins.AzureBlobCache/

My hope is that it replaced DiskCache for caching processed images.  When I couldn’t get it to work, I googled it, and ended up here.

So the way I understood it, it would work like this.

User uploads image to (local) image source store on website…something like http://www.kyaemedia.com/someimage.jpg  —> some page requests the image http://www.kyaemedia.com/someimage.jpg?height=100&width=100&mode=crop —> ImageProcessor would process the image, save it to the AzureBlobCache, then serve this image to the page with a CDN url to the image.

Is this how it works?

**Comment by JimBobSquarePants** [comment]
>User uploads image to (local) image source store on website…something like http://www.kyaemedia.com/someimage.jpg  —> some page requests the image http://www.kyaemedia.com/someimage.jpg?height=100&width=100&mode=crop —> ImageProcessor would process the image, save it to the AzureBlobCache, then serve this image to the page with a CDN url to the image.

Kinda....

1. A request for a local image is made via the page
2. ImageProcessor.Web intercepts the request, processes it, then sends it to the current cache to be saved.
3.  The AzureBlobCache sends the image to blob storage where it is then automatically copied by Azure to the cdn.
4. ImageProcessor.Web redirects the  request to the CDN url via a 302

Things to be aware of.

1. Your blob storage container must be public
2. The CDN can be slow when first set up and will generally take over an hour to start working properly (I've no idea why it takes Azure so long)

Documentation for the cache plugin is here. 

http://imageprocessor.org/imageprocessor-web/plugins/azure-blob-cache/

**Comment by troyfulton** [comment]
Ok, this is what I understood.  So this bring us back to the reason I contacted you.  I’ve followed the instructions, and cannot get it to work.  All of the information I’ve given you so far was assuming this is how it would work and how to use it.

Let me create a clean test environment to test, I’ll confirm CDN is functional etc…and see where we get.

With this being said, do I even need to modify the security .config?  Or just the Cache .config according to http://imageprocessor.org/imageprocessor-web/plugins/azure-blob-cache/?

**Comment by JimBobSquarePants** [comment]
I would double check all your settings and ensure everything is installed properly. A clean environment with a test would definitely be wise.

>With this being said, do I even need to modify the security .config?

No, the security config is for the `IImageService` implementations. Mostly the RemoteImageService.

**Comment by troyfulton** [comment]
Ok, thank you….I’ll let you know either way.

**Comment by JimBobSquarePants** [comment]
No worries.

**Comment by troyfulton** [comment]
Ok,

I have a clean install and confirmed my azure CDN has propagated…here is my config. When I try to process a local image, It returns 404…however, it does successfully process the image and stores the processed image into the my azure  container named “can” …it just won’t return it to me:

Screen Shots: http://www.screencast.com/t/CoDpAJ3A2 , http://www.screencast.com/t/vLQp2xrg

Any Ideas?

<?xml version="1.0" encoding="utf-8"?>
<caching currentCache="AzureBlobCache">
  <caches>
    <cache name="DiskCache" type="ImageProcessor.Web.Caching.DiskCache, ImageProcessor.Web" maxDays="365">
      <settings>
        <setting key="VirtualCachePath" value="~/app_data/cache" />
      </settings>
    </cache>
  <cache name="AzureBlobCache"  type="ImageProcessor.Web.Plugins.AzureBlobCache.AzureBlobCache, ImageProcessor.Web.Plugins.AzureBlobCache" maxDays="365">
      <settings>
        <setting key="CachedStorageAccount" value="DefaultEndpointsProtocol=https;AccountName=kyaimages;AccountKey=/2tWaEuGWVeqKsIdQaiKbXoUvgt+4wyKRjC2MS3OervD30Sf4+chPnr3yMbj76dCsmxCIz3npIAIV3uz0zUq7w==" />
        <setting key="CachedBlobContainer" value="cdn" />
        <setting key="CachedCDNRoot" value="http://imagecdn.kyamedia.com" />
        <setting key="SourceStorageAccount" value="" />
        <setting key="SourceBlobContainer" value="" />
        <setting key="StreamCachedImage" value="false" />
      </settings>
    </cache></caches>
</caching>

**Comment by troyfulton** [comment]
I meant to send you this test URL

http://elysian.kyamedia.com/light.jpg?width=500&heigth=100&mode=crop

From: Robert Fulton <troy.fulton@kyamedia.com<mailto:troy.fulton@kyamedia.com>>
Date: Thursday, February 4, 2016 at 9:58 PM
To: "JimBobSquarePants/UmbracoFileSystemProviders.Azure" <reply@reply.github.com<mailto:reply@reply.github.com>>, "JimBobSquarePants/UmbracoFileSystemProviders.Azure" <UmbracoFileSystemProviders.Azure@noreply.github.com<mailto:UmbracoFileSystemProviders.Azure@noreply.github.com>>
Subject: Re: [UmbracoFileSystemProviders.Azure] Azure Blob Cache (#24)

Ok,

I have a clean install and confirmed my azure CDN has propagated…here is my config. When I try to process a local image, It returns 404…however, it does successfully process the image and stores the processed image into the my azure  container named “can” …it just won’t return it to me:

Screen Shots: http://www.screencast.com/t/CoDpAJ3A2 , http://www.screencast.com/t/vLQp2xrg

Any Ideas?

<?xml version="1.0" encoding="utf-8"?>
<caching currentCache="AzureBlobCache">
  <caches>
    <cache name="DiskCache" type="ImageProcessor.Web.Caching.DiskCache, ImageProcessor.Web" maxDays="365">
      <settings>
        <setting key="VirtualCachePath" value="~/app_data/cache" />
      </settings>
    </cache>
  <cache name="AzureBlobCache"  type="ImageProcessor.Web.Plugins.AzureBlobCache.AzureBlobCache, ImageProcessor.Web.Plugins.AzureBlobCache" maxDays="365">
      <settings>
        <setting key="CachedStorageAccount" value="DefaultEndpointsProtocol=https;AccountName=kyaimages;AccountKey=/2tWaEuGWVeqKsIdQaiKbXoUvgt+4wyKRjC2MS3OervD30Sf4+chPnr3yMbj76dCsmxCIz3npIAIV3uz0zUq7w==" />
        <setting key="CachedBlobContainer" value="cdn" />
        <setting key="CachedCDNRoot" value="http://imagecdn.kyamedia.com" />
        <setting key="SourceStorageAccount" value="" />
        <setting key="SourceBlobContainer" value="" />
        <setting key="StreamCachedImage" value="false" />
      </settings>
    </cache></caches>
</caching>

**Comment by troyfulton** [comment]
Hello,

Like we talked about, I have a clean install and confirmed my azure CDN has propagated…here is my config. When I try to process a local image, It returns 404…however, it does successfully process the image and stores the processed image into the my azure  container named “can” …it just won’t return it to me:

Screen Shots: http://www.screencast.com/t/CoDpAJ3A2 , http://www.screencast.com/t/vLQp2xrg

Test URL:  http://elysian.kyamedia.com/light.jpg?width=500&heigth=100&mode=crop

I really want to use your product, but I need this piece to work.  Please let me know how I can help get this solved.  Thank you in advance.

<?xml version="1.0" encoding="utf-8"?>
<caching currentCache="AzureBlobCache">
  <caches>
    <cache name="DiskCache" type="ImageProcessor.Web.Caching.DiskCache, ImageProcessor.Web" maxDays="365">
      <settings>
        <setting key="VirtualCachePath" value="~/app_data/cache" />
      </settings>
    </cache>
  <cache name="AzureBlobCache"  type="ImageProcessor.Web.Plugins.AzureBlobCache.AzureBlobCache, ImageProcessor.Web.Plugins.AzureBlobCache" maxDays="365">
      <settings>
        <setting key="CachedStorageAccount" value="DefaultEndpointsProtocol=https;AccountName=kyaimages;AccountKey=/2tWaEuGWVeqKsIdQaiKbXoUvgt+4wyKRjC2MS3OervD30Sf4+chPnr3yMbj76dCsmxCIz3npIAIV3uz0zUq7w==" />
        <setting key="CachedBlobContainer" value="cdn" />
        <setting key="CachedCDNRoot" value="http://imagecdn.kyamedia.com" />
        <setting key="SourceStorageAccount" value="" />
        <setting key="SourceBlobContainer" value="" />
        <setting key="StreamCachedImage" value="false" />
      </settings>
    </cache></caches>
</caching>

From: Robert Fulton <troy.fulton@kyamedia.com<mailto:troy.fulton@kyamedia.com>>
Date: Thursday, February 4, 2016 at 10:32 PM
To: "JimBobSquarePants/UmbracoFileSystemProviders.Azure" <reply@reply.github.com<mailto:reply@reply.github.com>>, "JimBobSquarePants/UmbracoFileSystemProviders.Azure" <UmbracoFileSystemProviders.Azure@noreply.github.com<mailto:UmbracoFileSystemProviders.Azure@noreply.github.com>>
Subject: Re: [UmbracoFileSystemProviders.Azure] Azure Blob Cache (#24)

I meant to send you this test URL

http://elysian.kyamedia.com/light.jpg?width=500&heigth=100&mode=crop

From: Robert Fulton <troy.fulton@kyamedia.com<mailto:troy.fulton@kyamedia.com>>
Date: Thursday, February 4, 2016 at 9:58 PM
To: "JimBobSquarePants/UmbracoFileSystemProviders.Azure" <reply@reply.github.com<mailto:reply@reply.github.com>>, "JimBobSquarePants/UmbracoFileSystemProviders.Azure" <UmbracoFileSystemProviders.Azure@noreply.github.com<mailto:UmbracoFileSystemProviders.Azure@noreply.github.com>>
Subject: Re: [UmbracoFileSystemProviders.Azure] Azure Blob Cache (#24)

Ok,

I have a clean install and confirmed my azure CDN has propagated…here is my config. When I try to process a local image, It returns 404…however, it does successfully process the image and stores the processed image into the my azure  container named “can” …it just won’t return it to me:

Screen Shots: http://www.screencast.com/t/CoDpAJ3A2 , http://www.screencast.com/t/vLQp2xrg

Any Ideas?

<?xml version="1.0" encoding="utf-8"?>
<caching currentCache="AzureBlobCache">
  <caches>
    <cache name="DiskCache" type="ImageProcessor.Web.Caching.DiskCache, ImageProcessor.Web" maxDays="365">
      <settings>
        <setting key="VirtualCachePath" value="~/app_data/cache" />
      </settings>
    </cache>
  <cache name="AzureBlobCache"  type="ImageProcessor.Web.Plugins.AzureBlobCache.AzureBlobCache, ImageProcessor.Web.Plugins.AzureBlobCache" maxDays="365">
      <settings>
        <setting key="CachedStorageAccount" value="DefaultEndpointsProtocol=https;AccountName=kyaimages;AccountKey=/2tWaEuGWVeqKsIdQaiKbXoUvgt+4wyKRjC2MS3OervD30Sf4+chPnr3yMbj76dCsmxCIz3npIAIV3uz0zUq7w==" />
        <setting key="CachedBlobContainer" value="cdn" />
        <setting key="CachedCDNRoot" value="http://imagecdn.kyamedia.com" />
        <setting key="SourceStorageAccount" value="" />
        <setting key="SourceBlobContainer" value="" />
        <setting key="StreamCachedImage" value="false" />
      </settings>
    </cache></caches>
</caching>

**Comment by JimBobSquarePants** [comment]
Try putting a slash at the end of the CDN root config value. e.g. `http://imagecdn.kyamedia.com/`

Also, change all your credentials.

**Comment by troyfulton** [comment]
I’ve tried with and with out the trailing slash…same result.

So, when you say Change All Credentials…so you mean AccountKey or ???

**Comment by JimBobSquarePants** [comment]
Yeah... You've published all your account details in this thread. Anyone can log into your setup now. 

Tell you what... If you send me an email james_south@hotmail.com With your new details I'll create a solution with everything setup for you to copy. Won't be today I'm afraid though, maybe tomorrow or Monday.

**Comment by troyfulton** [comment]
You got it I just shut everything down because it's late here but I will email you the new credentials tomorrow.

Troy Fulton / Director of Research and Development
cell: 303.378.5040<tel:303.378.5040>/ troy.fulton@kyamedia.com<mailto:troy.fulton@kyamedia.com>

KYA Media
Office: 303.997.3230 x700<tel:303.997.3230;700>
4833 Front Street. B207
Castle Rock, CO 80104
http://www.kyamedia.com




On Fri, Feb 5, 2016 at 9:34 PM -0800, "James Jackson-South" <notifications@github.com<mailto:notifications@github.com>> wrote:


Yeah... You've published all your account details in this thread. Anyone can log into your setup now.

Tell you what... If you send me an email james_south@hotmail.com<mailto:james_south@hotmail.com> With your new details I'll create a solution with everything setup for you to copy. Won't be today I'm afraid though, maybe tomorrow or Monday.

-

**Comment by troyfulton** [comment]
Hi James,

Not sure if you saw, but I sent you my credentials to your hotmail account.  I wasn’t sure if it went to junk or not, but wanted to let you know.

Thanks for all of your help.

Troy

**Comment by JimBobSquarePants** [comment]
Hi Troy,

Sorry, I've not had the opportunity to knock up a demo yet, I'll do so asap. Just to double check... Is the CDN you set up still active and set up at the same url?

Cheers

James

Date: Tue, 9 Feb 2016 08:10:04 -0800

**Comment by troyfulton** [comment]
Thanks for getting back to me, and yes it’s all still setup and ready.  I’ve also created a custom domain that is pointing to the CDN as well…and it’s active.  http://imagecache.kyamedia.com<http://imagecache.kyamedia.com/>

There is an image called light.jpg the you can use to confirm it’s all configured and available.

http://kyaimages.blob.core.windows.net/cdn/light.jpg
http://kyaimagecdn.azureedge.net/light.jpg
http://imagecache.kyamedia.com/light.jpg

Thanks again!

**Comment by JimBobSquarePants** [comment]
Thanks for that. At work just now but will attack it after.

**Comment by troyfulton** [comment]
Ok, thanks again!  I really appreciate it.

**Comment by troyfulton** [comment]
Hey bro, I hate to be the squeaky wheel, but I’m just checking in to see if there is any progress?

Thanks,

Troy

**Comment by JimBobSquarePants** [comment]
Hi Troy,

I've been trying to get the Azure cache working with your set up and I've determined where the code is failing.

``` c#
CloudBlobContainer container = cloudBlobClient.GetContainerReference(containerName);
container.CreateIfNotExists(); // Error is thrown here.
container.SetPermissions(new BlobContainerPermissions { PublicAccess = accessType });
return container;
```

This throws with the error.
>The remote name could not be resolved: 'kyamiages.blob.core.windows.net'

This is all standard Azure.SDK calls I am making so there must be something up with the configuration of your blob and CDN settings.

I've spotted something odd in that your blob container account url and cdn url both begin with the same domain. http://kyaimages.blob.core.windows.net. That should be the domain to your storage account only.

According to the documentation CDN custom domains should be subdomains of your website not the storage url.

>Manage custom domains

>You can map a custom domain name to your Windows Azure CDN endpoint. Windows Azure must verify that you are authorized to modify DNS records for the domain. To verify authorization, create a CNAME resource record with your DNS provider that points from [subdomain].yourdomain.com to az123456.vo.msecnd.net, or from cdnverify.[subdomain].yourdomain.com to cdnverify.az123456.vo.msecnd.net.

I would set up your account so that you are not using custom domains for now and test against that. Once you have it working you could then setup a custom domain if you see fit.

**Comment by troyfulton** [comment]
Hi James,

So, the storage resource is just named kyaimages, It’s not associated with any custom domains.  http://www.screencast.com/t/62MqGVCf

Also, I’ve tried using the CDN name that Azure assigns and the custom domain in the CachedCDNRoot field, and they both respond the same…however, they both are public and you can access resources in a browser.  http://www.screencast.com/t/E6XWxO4ZMVBe

Also, these were setup in the new Azure portal versus the classic portal.  I’m not sure that it should make a difference, but just FYI.  I wanted to mention it because I see all the CDN documentation talks about a CDN URL with the following naming convention: az123456.vo.msecnd.net  and now when you create a CSN, it has a {name}.azureedge.net naming convention.


Troy

**Comment by troyfulton** [comment]
Let me ask this

        <setting key="CachedBlobContainer" value="cdn" />
        <setting key="CachedCDNRoot" value="http://kyaimagecdn.azureedge.net" />

With my settings as such, the image is getting processed and stored in the folder structures under the “cdn” container indicated in “CachedBlobContainer”…so we know it’s getting processed and that part is fine.

I think the issue in retrieval.  So with my “CachedCDNRoot” having a value of "http://kyaimagecdn.azureedge.net/“  when your code uses it to render the image back to the browser, will it append “CachedBlobContainer” value?  So will it look something like:

http://kyaimagecdn.azureedge.net/cdn/f/0/r/5/g/e/6/g/image.jpg

OR

http://kyaimagecdn.azureedge.net/f/0/r/5/g/e/6/g/image.jpg

**Comment by Jeavon** [comment]
Could you post a full url copied from the storage account in the Azure portal to a single image? And does it show up? Also could you try a container that isn't CDN, e.g cache (I have a vague recollection about the CDN path being special)

**Comment by JimBobSquarePants** [comment]
@troyfulton It would append the `cdn` value, for example

http://az833440.vo.msecnd.net/cache/4/8/9/a/4/d/489a4d535480ca6b8a38695f28c5f405dbfb30f6.jpg

I'm not able to even get as far as processing an image. As soon as I attempt to check for the existence of a container I get the failure, hence the error above. 

I just tried to log into the storage account using http://www.cloudberrylab.com/free-microsoft-azure-explorer.aspx and I got the exact same error. 

Are there any permissions settings for the storage account?

**Comment by troyfulton** [comment]
Yes.

BLOB: http://kyaimages.blob.core.windows.net/cdn/light.jpg
CDN: http://kyaimagecdn.azureedge.net/light.jpg
Custom Domain with CNAME to CDN: http://imagecache.kyamedia.com/light.jpg

**Comment by troyfulton** [comment]
No, permission settings are all set to public.  And I can tell you that the image does process and gets saved in the BLOB storage.

You can check out all the URL’s here.


BLOB: http://kyaimages.blob.core.windows.net/cdn/light.jpg
CDN: http://kyaimagecdn.azureedge.net/light.jpg
Custom Domain with CNAME to CDN: http://imagecache.kyamedia.com/light.jpg

**Comment by JimBobSquarePants** [comment]
I can see those urls but they are not processed urls. I.E, they're not in a cache folder.

I'm stepping through the code here and I am definitely not processing any images. Azure throws an error long before any caching takes place.

**Comment by troyfulton** [comment]
So, when I call this URL:

http://elysian.kyamedia.com/light.jpg?height=100&width=400&mode=crop

It processes the light.jpg image, I can see it create a folder structure and image in the BLOB right on Azure Console:  http://www.screencast.com/t/Eb1XFfLbq

I’ve done it a number of times trying different configurations.  Here is just one of the resulting processed images.

https://kyaimages.blob.core.windows.net/cdn/f/c/c/f/7/1/fccf71fb98d966ff95fc3b9d6d69f4eebfdd0ba3.jpg

**Comment by troyfulton** [comment]
If you’re up for it, We could do a GoToMeeting were we can share the screen just go through it together.

**Comment by JimBobSquarePants** [comment]
Solved it!

As far as I can gather there seems to be a change in the way Azure are processing CDN urls. So if you have the container name in the url you will now get a 404.

I've just released an update to [AzureBlobCache](https://www.nuget.org/packages/ImageProcessor.Web.Plugins.AzureBlobCache/1.0.8) that adds a new configuration value to allow you to pick whether this should happen or not.

Once installed your configuration should be:

``` xml
<caching currentCache="AzureBlobCache">
  <caches>
    <!-- Disk cache configuration removed for brevity -->
    <cache name="AzureBlobCache" type="ImageProcessor.Web.Plugins.AzureBlobCache.AzureBlobCache, ImageProcessor.Web.Plugins.AzureBlobCache" maxDays="365">
      <settings>
        <!-- The Account, Container and CDN details -->
        <setting key="CachedStorageAccount" value="DefaultEndpointsProtocol=https;AccountName=kyamiages;AccountKey=[CacheAccountKey]"/>
        <setting key="CachedBlobContainer" value="cdn"/>
        <!-- Whether to add the container name to the CDN url. Newer Azure formats require false. -->
        <setting key="UseCachedContainerInUrl" value="false"/>
        <!-- Full CDN root url e.g http://123456.vo.msecnd.net/ -->
        <setting key="CachedCDNRoot" value="http://kyaimagecdn.azureedge.net/"/>
        <!-- 
            Optional settings for better identifcation of source images if stored in 
            Azure blob storage.
         -->
        <setting key="SourceStorageAccount" value=""/>
        <setting key="SourceBlobContainer" value=""/>
        <!-- 
            Optional settings facilitate streaming of the blob resource directly instead of a redirect. This is beneficial
            for CDN purposes but caution should be taken if not used with a CDN as it will add quite a bit of overhead 
            to the site. 
         -->
        <setting key="StreamCachedImage" value="false"/>
      </settings>
    </cache>
  </caches>
</caching> 
```

I've been testing it and it works flawlessly now.

Thanks for being so persistent. I wish we could move this to the correct bug tracker though! :stuck_out_tongue:

**Comment by troyfulton** [comment]
Excellent!  It works!  Thank you for sticking with this.

**Comment by Jeavon** [comment]
Well done! This only happens if you add a origin path to your CDN endpoint, generally you wouldn't do this...

![capture](https://cloud.githubusercontent.com/assets/1829920/12979499/87f74130-d0cf-11e5-8b43-1289824aaf35.PNG)

**Comment by troyfulton** [comment]
Yes I found this to be true also however Azure will not let you not have an origin path.  It won't even let you just have a /

I have another question though I've got a scenario where I need to do a moody quotes crop in the mood equal stretch if I use mowed twice in the URL will it processed the commands?

Troy Fulton / Director of Research and Development
cell: 303.378.5040<tel:303.378.5040>/ troy.fulton@kyamedia.com<mailto:troy.fulton@kyamedia.com>

KYA Media
Office: 303.997.3230 x700<tel:303.997.3230;700>
4833 Front Street. B207
Castle Rock, CO 80104
http://www.kyamedia.com




On Thu, Feb 11, 2016 at 6:56 AM -0800, "Jeavon" <notifications@github.com<mailto:notifications@github.com>> wrote:


Well done! This only happens if you add a origin path to your CDN endpoint, generally you wouldn't do this...

[capture]<https://cloud.githubusercontent.com/assets/1829920/12979499/87f74130-d0cf-11e5-8b43-1289824aaf35.PNG>

-

**Comment by Jeavon** [comment]
Yes it will, just leave it blank???

**Comment by troyfulton** [comment]
It won't let you leave a blank either you have to put an actual path in there

Troy Fulton / Director of Research and Development
cell: 303.378.5040<tel:303.378.5040>/ troy.fulton@kyamedia.com<mailto:troy.fulton@kyamedia.com>

KYA Media
Office: 303.997.3230 x700<tel:303.997.3230;700>
4833 Front Street. B207
Castle Rock, CO 80104
http://www.kyamedia.com




On Thu, Feb 11, 2016 at 8:20 AM -0800, "Jeavon" <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes it will, just leave it blank???

-

**Comment by Jeavon** [comment]
Odd, I can leave it blank no problem...?
![capture](https://cloud.githubusercontent.com/assets/1829920/12982596/524a7c60-d0dd-11e5-831c-c49f614e1170.PNG)

**Comment by troyfulton** [comment]
That's really weird I've tried several times and it just would never let me I get a error message saying that I can't save it.

Troy Fulton / Director of Research and Development
cell: 303.378.5040<tel:303.378.5040>/ troy.fulton@kyamedia.com<mailto:troy.fulton@kyamedia.com>

KYA Media
Office: 303.997.3230 x700<tel:303.997.3230;700>
4833 Front Street. B207
Castle Rock, CO 80104
http://www.kyamedia.com




On Thu, Feb 11, 2016 at 8:34 AM -0800, "Jeavon" <notifications@github.com<mailto:notifications@github.com>> wrote:


Odd, I can leave it blank no problem...?
[capture]<https://cloud.githubusercontent.com/assets/1829920/12982596/524a7c60-d0dd-11e5-831c-c49f614e1170.PNG>

-

**Comment by troyfulton** [comment]
Check this out.

Empty: http://www.screencast.com/t/WcHWhay5
Root path: http://www.screencast.com/t/oA6VXcrBuKE

**Comment by Jeavon** [comment]
Whoa, the UI is different! I'm spinning up a CDN is West US right now to see if it's about where it's located as mine is in Europe West

**Comment by troyfulton** [comment]
Yea, interesting…also, I’m using resource groups not classic.  It might make the difference in a few areas.

**Comment by Jeavon** [comment]
Exactly same UI on West US. I also am using Resource Groups, actually you cannot provision a CDN in the new portal unless it is using Resource Groups.

Really bizarre!

![capture](https://cloud.githubusercontent.com/assets/1829920/12983679/367ec126-d0e2-11e5-9550-0be4b071cc77.PNG)

**Comment by troyfulton** [comment]
Yea, bizzarre, but it helps mature the product for sure!

**Comment by Jeavon** [comment]
Yes, but you shouldn't have to have a Origin path!

**Comment by troyfulton** [comment]
I agree, it’s likely a bug on their end…I’ve had a few issues transitioning from classic to resource groups and the new portal.

**Comment by Jeavon** [comment]
Ok, so was this CDN transitioned from the classic portal automatically then?

**Comment by troyfulton** [comment]
No, it’s from scratch in Resource Groups…but when I initially created them, it took over a week for the CDN to become active…in fact, I had to submit a support ticket…so I think they made it active.

**Comment by Jeavon** [comment]
Hmm, when you are on the Endpoint and you click "Configure" what do you get in the next blade?

**Comment by troyfulton** [comment]
http://www.screencast.com/t/OVuxiPm0tm

http://www.screencast.com/t/T3xhFefGt7

**Comment by Jeavon** [comment]
Odd, I would raise a ticket with support I were you, something is up in there!
Maybe try a test new CDN and see if you can create a endpoint/origin without any origin path..

**Comment by troyfulton** [comment]
Yea, I think I will raise the ticket.  I already tried new CDN without including a path, I tried adding the CDN to my existing storage versus spinning up this new one…I tried every conceivable combination trying to get your stuff to work before reaching out to you.  So, I think you’re right, something’s going on.

**Comment by Jeavon** [comment]
At least you have screens shots showing what it does normally! Good luck!

**Comment by troyfulton** [comment]
Thanks for all of your help, I appreciate it.
