### ISSUE TITLE
Add support for SAS tokens

### ISSUE THREAD

**Issue by paulsterling** [JimBobSquarePants/UmbracoFileSystemProviders.Azure#25]
To allow the use a single service endpoint with multiple containers where the SAS token is set per container - as in the case of multiple-tenants using a single storage service.  This will remove the need to store the admin-level access-key in the app's web.config and will also storage admins to set SAS at the policy level, which could later be revoked if needed.
Working on PR and will update with comments and questions in my fork.

**Comment by JimBobSquarePants** [comment]
I'm glad you're working on a PR cos I understood about 10% of that!

**Comment by Jeavon** [comment]
Sounds great Paul! 

I think for SAS tokens we will need to update the WindowsAzure.Storage dependency to at least v5.0.2 (we currently have v4.3.0) which through a shared dependency on Newtonsoft.Json (it's always that one) means that minimum compatibility will go up to Umbraco v7.1.1, of course meaning no Umbraco v6.2 support.

IMO, we should update to WindowsAzure.Storage v6.2 anyway and Umbraco minimum v7.1.1. If anyone really wants to use the package in Umbraco v6.2 or v7.0 (you would have to be crazy), they can use the v0.5.1 release.

Thoughts anyone?

**Comment by JimBobSquarePants** [comment]
@Jeavon Agreed. Time to move on.

**Comment by paulsterling** [comment]
@JimBobSquarePants and @Jeavon For sure...this would target 7.3+ (maybe 7.4+ as I've run into a new issue).  In any case, planning on using v.latest of WindowsAzure.Storage - so we agree on that.
Plan is to not change the current behavior and only support SAS tokens if specified.  At least one change will be that using container level SAS we won't be able to create the root (i.e., "media") container but will assume it's already been created - as I believe makes sense else the SAS token cannot be generated in the first place.

**Comment by Jeavon** [comment]
@paulsterling sounds great. I've just committed updating to the latest stable Azure releases and therefore upgrading our Umbraco dependency to minimum v7.1.9 so you may want to pull the latest develop branch commits into your development.

At the moment, I don't see any reason why we would need to up the minimum beyond v7.1.9 but see what you find and if it's required.

Thanks!

**Comment by Jeavon** [comment]
With regard to containers not being part of the path when using tokens I think it would probably relate to this issue also https://github.com/JimBobSquarePants/UmbracoFileSystemProviders.Azure/issues/26

**Comment by idseefeld** [comment]
@paulsterling I need SAS features too in my current project. I have started with forking your branch and reading through Microsoft docs. Currently I am planning to use at least two containers, one private and the other public. Back office control should be done by MediaProtect package. Let's se what I will come up with. Maybe we can discuss at CodeGarden? I'll be there.

**Comment by paulsterling** [comment]
@idseefeld I'll miss you at CG this year but happy to discuss online.  I have a corresponding controller that creates the tokens and containers with specific access policies.  Will dig that out and send directly to you.

**Comment by joecklau** [comment]
May I know whether the SAS is supported?

**Comment by idseefeld** [comment]
@joecklau No, currently this is not supported. But I'll have a look into this within the next days - no guaranty of course;-)
Stay tuned...

**Comment by idseefeld** [comment]
good news!
With the upcoming release version 1.1.0-beta a bug, which prevents the use of sas tokens, will be fixed. I expect the release within a few days, as Jeavon is working on another fix regarding TSL security.
