### ISSUE TITLE
Add option to configure the Umbraco media prefix to be different to the container name

### ISSUE THREAD

**Issue by Jeavon** [JimBobSquarePants/UmbracoFileSystemProviders.Azure#26]
I may want to use a custom container name such as "clientName_media" but I want Umbraco to keep serving media from the "media" (or other custom) prefix

**Comment by JimBobSquarePants** [comment]
Just having a quick look at this. I don't think it's that difficult. 

https://github.com/JimBobSquarePants/UmbracoFileSystemProviders.Azure/blob/develop/src/UmbracoFileSystemProviders.Azure/AzureFileSystem.cs#L598

The trick would be to check for either the root, container name or the alias. That _should_ allow for us to use different naming.

**Comment by technicallyerik** [comment]
I would also like to independently set a different "containerName" in FileSystemProviders.config and  "location path" for the virtual path provider in the web.config.

**Comment by Jeavon** [comment]
@JimBobSquarePants I'm happy with the independent-container branch now. Perhaps @technicallyerik would be up for testing once we've merged and there's a pre-release available?

**Comment by JimBobSquarePants** [comment]
@Jeavon I'll merge it in.

**Comment by Jeavon** [comment]
Fab @JimBobSquarePants ! @technicallyerik v0.5.2-beta-000088 or above has this new feature if you are up for testing it out

**Comment by technicallyerik** [comment]
I'll give it a try this week, thanks!

**Comment by JimBobSquarePants** [comment]
Hi @technicallyerik Did you ever get the chance to test this?

**Comment by technicallyerik** [comment]
Hey @JimBobSquarePants unfortunately I haven't.  My current project is Umbraco 6.2.5, and it looks like at some point this package was updated to only support v7.1.9+.

**Comment by JimBobSquarePants** [comment]
Oh, I'll need to wrack my brain as to why we did this. @Jeavon Any idea?

**Comment by Jeavon** [comment]
@JimBobSquarePants yes, because we want to support SAS tokens which requires WindowsAzure.Storage v6 which has a dependency which requires Newtonsoft.Json v6 which means Umbraco v7.1.9. It's always Newtonsoft.Json that forces updates.

**Comment by JimBobSquarePants** [comment]
@Jeavon Ah yes, that's the one. Thanks!
