### ISSUE TITLE
VPP not intercepting / serving assets from Azure Blob

### ISSUE THREAD

**Issue by lemining** [JimBobSquarePants/UmbracoFileSystemProviders.Azure#27]
Hi,

Good work on this package - it has been really helpful so far to help me understand how to integrate Azure Blob storage with Umbraco.

I have a vanilla setup of Umbraco (7.3.4). I have downloaded and setup your package (as per your documentation).

It seems that when I upload new images via back office - they do get uploaded to the blob, however it seems that VPP is not intercepting requests and I always get http://puu.sh/n9hsM/bc180eda5b.png -Server Error in '/' Application. The resource cannot be found.

It seems that if I put the file locally in the media folder it gets loaded fine - which makes me think that VPP is not initialized automatically. Do I need to explicitly reference it anywhere?

I thought I would ask before downloading source code etc.

Thanks!

**Comment by JimBobSquarePants** [comment]
Hi there,

Are you using a website or a web application. (Websites do not support VPP) Also do your config files match the ones specified in the readme? 

It should all work out of the box with the VPP enabled by default.

Cheers

James

**Comment by lemining** [comment]
I have tried it on IIS Express, separate standalone server (IIS) and Azure webApplications. 

Config files are setup correctly, no image processor nor caching though. 

Am I suppose to leave Static handler on in production?

Cheers,
Luke

**Comment by JimBobSquarePants** [comment]
> Are you using a website or a web application?

Still not sure what you're running chum.

What do you mean no ImageProcessor? have you disabled the HttpModule?

No - The static handler should be ok as far as I'm aware.

Cheers

James

**Comment by lemining** [comment]
Ok, I have spent some time with it. It seems that if you want to use UmbracoFileSystemProviders.Azure on vanilla Umbraco (without installing configuration package for image re sizing).

You need to comment out ImageProcessorModule (there are two of those so make sure you comment out both).

`<add name="ImageProcessorModule" type="ImageProcessor.Web.HttpModules.ImageProcessingModule, ImageProcessor.Web" />`

I'll be installing configuration package next to see how that works all together. 

Thanks for your help!

**Comment by JimBobSquarePants** [comment]
My pleasure!

>You need to comment out ImageProcessorModule (there are two of those so make sure you comment out both).
>
>`<add name="ImageProcessorModule" type="ImageProcessor.Web.HttpModules.ImageProcessingModule, ImageProcessor.Web" />`

Yeah that's how you would disable ImageProcessor.Web (I wrote that too btw) Though you shouldn't need to if you have a version higher than 4.4.0 installed as it will only kick in when there are querystring parameters.

I'd definitely recommend using ImageProcessor with Umbraco though and installing/setting up the additional configuration files via [Nuget](https://www.nuget.org/packages/ImageProcessor.Web.Config/) will let you wire up everything properly.

I'm glad you're getting to grips with the library, if you have any issues at all don't hesitate to get in touch. :smile:

**Comment by lemining** [comment]
Definitely agree! 

I like to work though things step by step hence why I wanted to start off without ImageProcessor.

Thank you, once again!
