### ISSUE TITLE
Media uploaded both locally and to Azure blob container

### ISSUE THREAD

**Issue by oooshola** [JimBobSquarePants/UmbracoFileSystemProviders.Azure#29]
Hello there!

Has anyone come across this problem?: When uploading media, the file is saved both to the local webserver **and** to the blob container, rather than just to the blob container. For example:

web server: http://operations.nfl.com/live/2091/home-hero-sb50-manning.jpg
blob container: http://uaasnfl.blob.core.windows.net/live/2091/home-hero-sb50-manning.jpg

I've verified that the physical files are actually there in both of the above locations (i.e. no weird rewriting is going on).

A couple of other facts: this is on Umbraco as a Service, v7.3.8. Also, this only began happening at the beginning of February, if that at all matters/helps. We're using v0.5.0-beta of this plugin.

Everything else works properly, but in a multi-environment setup, pushing lots of large local media files (that are never actually used) through environments is something we'd like to avoid.

Cheers!

**Comment by JimBobSquarePants** [comment]
Hi there,

Can I see your configuration file? 

I wonder if Umbraco have introduced a bug.

**Comment by oooshola** [comment]
Hi @JimBobSquarePants , Do you want to see web.config, or the imageprocessor config files? or FileSystemProviders.config?

**Comment by JimBobSquarePants** [comment]
Just `FileSystemProviders.config` for now please. It should contains everything we are using for the media section.

**Comment by oooshola** [comment]
Here you go:

```
<?xml version="1.0"?>
<FileSystemProviders>

  <!-- Media -->  
  <Provider alias="media" type="Our.Umbraco.FileSystemProviders.Azure.AzureBlobFileSystem, Our.Umbraco.FileSystemProviders.Azure">
    <Parameters>
      <add key="containerName" value="live" />
      <add key="rootUrl" value="http://uaasnfl.blob.core.windows.net/" />
      <add key="connectionString" value="DefaultEndpointsProtocol=https;AccountName=uaasnfl;AccountKey=XXXXX"/>
      <!--
        Optional configuration value determining the maximum number of days to cache items in the browser.
        Defaults to 365 days.
      -->
      <add key="maxDays" value="365" />
    </Parameters>
  </Provider>
  

</FileSystemProviders>

```

**Comment by oooshola** [comment]
Hello there, any ideas on this? Would more info help?

Cheers

**Comment by Jeavon** [comment]
@oooshola I tried with Umbraco v7.3.8 & v7.4.1 and I could not replicate. What version of Umbraco are you using and do you have any other media related packages installed?

**Comment by JimBobSquarePants** [comment]
@oooshola Sorry for the slow reply. I'm currently running this on two 7.4.1 sites and cannot replicate either. Your config looks fine to me btw. Unfortunately I cannot test on Umbraco as a service.

**Comment by oooshola** [comment]
Hello all,

After changing everything to reflect the container name to be "media" instead of "live", I stopped having the issue. No media items were saved into the local "media" directory, only in the blob container (also, obviously nothing in any local "live" directory neither).

Just thought you'd like to know--I'm happy with the result.

**Comment by JimBobSquarePants** [comment]
Ah right. I think there must have been a bug there somewhere then. We did some work recently to allow different container names so that will hopefully not be an issue in the future.
