### ISSUE TITLE
Only getting HTTP 200, never 304

### ISSUE THREAD

**Issue by bussemac** [JimBobSquarePants/UmbracoFileSystemProviders.Azure#30]
Using Umbraco 7.4.1, version 0.51 of this via nuget, and an Azure storage account (classic), I can serve media files and upload them fine, but I only ever get HTTP 200 back, so I'm not gaining any benefits of caching. Do I need a separate plugin? These are just simple requests, not being manipulated with ImageProcessor. I've reloaded the page a few times to make sure they should be cached. I'v

```
URL	Protocol	Method	Result	Type	Received	Taken	Initiator	Wait‎‎	Start‎‎	Request‎‎	Response‎‎	Cache read‎‎	Gap‎‎
/media/1246/sd9c_k0751_kaleidoscope_150.jpg	HTTP	GET	200	image/jpeg	9.90 KB	0.56 s	<img>	18954	234	265	63	0	3244
/media/1253/rd10_k0751_kaleidoscope_150.jpg	HTTP	GET	200	image/jpeg	7.50 KB	0.82 s	<img>	18954	499	297	31	0	2979
/media/1259/sd20b_k0751_kaleidoscope_150.jpg	HTTP	GET	200	image/jpeg	7.98 KB	0.59 s	<img>	18954	374	156	63	0	3213
```

Local requests like CSS files show 304:
```
URL	Protocol	Method	Result	Type	Received	Taken	Initiator	Wait‎‎	Start‎‎	Request‎‎	Response‎‎	Cache read‎‎	Gap‎‎
/css/stylesheet.css	HTTP	GET	304	text/css	139 B	249 ms	<link rel="stylesheet">	2590	0	249	0	0	24258
```

My FileSystemProviders.config:

`<Provider alias="media" type="Our.Umbraco.FileSystemProviders.Azure.AzureBlobFileSystem, Our.Umbraco.FileSystemProviders.Azure">
  	<Parameters>
  		<add key="containerName" value="media"/>
  		<add key="rootUrl" value="http://XXXX.blob.core.windows.net/"/>
  		<add key="connectionString"
  			value="DefaultEndpointsProtocol=https;AccountName=XXXXX;AccountKey=[redcated]"/>
  		
  		<add key="maxDays" value="365"/>
  	</Parameters>
  </Provider>`

My security.config: (this is the only service; others are commented out)
`<service prefix="media/" name="CloudImageService" type="ImageProcessor.Web.Services.CloudImageService, ImageProcessor.Web">
      <settings>
        <setting key="MaxBytes" value="8194304" />
        <setting key="Timeout" value="30000" />
        <setting key="Host" value="http://XXXX.blob.core.windows.net/media/" />
      </settings>
    </service>`

Any idea what I'm doing wrong here?

**Comment by bussemac** [comment]
I did try a non-classic storage account, too, but that didn't change anything.

**Comment by Jeavon** [comment]
You will need the ImageProcessor cache plugin also to get the redirects http://imageprocessor.org/imageprocessor-web/plugins/azure-blob-cache/

**Comment by bussemac** [comment]
Hm. I have that. Is there an example of which URLs to use where? Do I set the rootURL to the CDN endpoint in both FileSystemProviders.config and cache.config, and then the connectionString in FSP is to the actual media blob while the one in cache.config is to a different blob? There are example config files, but I haven't found a complete set that shows which URLs and which connection strings you'd plug in where.
