### ISSUE TITLE
Cannot push: 403

### ISSUE THREAD

**Issue by KennethJakobsen** [JimBobSquarePants/UmbracoFileSystemProviders.Azure#31]
Hi I've added support for Azure CDN but is unable to sync, I'm new to git. Do I need permission?

Regards
Kenneth

**Comment by JimBobSquarePants** [comment]
Hi Kenneth, 

You need to fork the repo, create a new branch then submit a pull request against this repo.

Github has a good set of instructions here.

https://help.github.com/categories/bootcamp/

Good luck!
