### ISSUE TITLE
404 getting images without setting width or height

### ISSUE THREAD

**Issue by teeto** [JimBobSquarePants/UmbracoFileSystemProviders.Azure#37]
Its a weird issue, i upload a media item and i can get the media only if i set width or height params. If not set i get a 404 error. In my local dev machine it works ok. I guess if not param set image request it is not going through image processor so:
If i set interceptAllRequests="true" in processing.config it works ok, but i dont know if i could get performance issues.
Why is this happening? it is a precompiled app, may be is it a virtual path issue?

**Comment by teeto** [comment]
I have published the app without precompiling and now it works. I think it is related to virtual path not working on precompiled sites.

**Comment by Jeavon** [comment]
Yes, VPPs don't work with precompiled sites.

**Comment by JimBobSquarePants** [comment]
@teeto If you are intent on precompiling the website it is possible to enable VPP's using reflection to run the required initialization code. It's hacky as hell but it might just help you.

http://sunali.com/2008/01/09/virtualpathprovider-in-precompiled-web-sites/
