### ISSUE TITLE
Allow derived implementations of AzureBlobFileSystem to be used

### ISSUE THREAD

**Issue by Philo** [JimBobSquarePants/UmbracoFileSystemProviders.Azure#39]
I am using the Umbraco azure file system provider along with image processor to store and off load media to blob storage, this works very well.  However the configuration requirements for the file system provider and image processor cache depend on reading configuration directly from the web.config file.  This behaviour is undesirable for us as it requires that sensitive keys and connection string need to be stored in source control as well as it not allowing us to deploy the same artifacts to multiple environments.

If solve this for other settings we are using the Azure `appSettings` and `connectionStrings` sections within the azure portal to manage configuration, this does not support custom sections.

I am able to created a derived class from `AzureBlobFileSystem` in which the configuration settings are set from another source (either appSettings or from umbraco itself) this file system can not be successfully registered due to the implementation within `VirtualPathProviderController`.

https://github.com/JimBobSquarePants/UmbracoFileSystemProviders.Azure/blob/develop/src/UmbracoFileSystemProviders.Azure/VirtualPathProviderController.cs#L42

The above code expects the file system is be of type `AzureBlobFileSystem`.  Would be it possible to alter this so that any class derived from `AzureBlobFileSystem` would be accepted

Altering:

```bool isAzureBlobFileSystem = fileSystem.GetType() == typeof(AzureBlobFileSystem);```

to:

```bool isAzureBlobFileSystem = fileSystem is AzureBlobFileSystem;```

With this I can use a custom implementation of the AzureBlobFileSystem.

**Comment by JimBobSquarePants** [comment]
Sounds like a small reasonable change. Could you PR?
