### ISSUE TITLE
Images stopped showing up on the back-end

### ISSUE THREAD

**Issue by vonbv** [JimBobSquarePants/UmbracoFileSystemProviders.Azure#42]
We've been using the package for several months now and it worked perfect until a few days ago. When a user uploads an image on the back-end it doesn't show up (see attached image). We are also using Azure cdn and I checked the container and the file is there. I've updated to the latest 0.5.1-beta version but it didn't solve the problem. I checked our configuration and nothing changed. What did I miss?
![empty_image](https://cloud.githubusercontent.com/assets/870921/14983753/b2c94114-1171-11e6-9abf-37cdd3efdfca.png)

**Comment by JimBobSquarePants** [comment]
I'm afraid I can only surmise something else must have changed in your codebase if the plugin worked perfectly before. Are there any error logs, have there been any recent commits?

**Comment by vonbv** [comment]
Is there anything that could affect the plugin from any part of our code? My understanding is that it won't be affected especially if we're not doing anything special when uploading images on the back-end? 

There are no errors showing up during and after the upload. The images before and after the issue have the same format "/media/{ID}/{filename}". It's a weird thing that for new images, Umbraco seems to look for it in the local path and not from the container.

**Comment by JimBobSquarePants** [comment]
>Is there anything that could affect the plugin from any part of our code? 

Only missing/misconfigured configuration and/or the absence of the binaries themselves. 

So you're saying that the images are still getting uploaded to blob storage but are not then retrievable by the back office? 

Are you absolutely sure that no changes have taken place to the website in that timeframe either configuration or code?  

- Have you added any routing or url rewriting recently?
- Have there been any configuration changes made on Azure?

I would double check the FileSystemProviders.config and Web.config files to ensure that they match the examples given in the readme. I'm wondering if your VirtualPathProvider setting have been changed or removed.

**Comment by vonbv** [comment]
> So you're saying that the images are still getting uploaded to blob storage but are not then retrievable by the back office?

Yes that's right. That's the first thing I checked to make sure the files are actually written/saved somewhere. The container have the them.

> Are you absolutely sure that no changes have taken place to the website in that timeframe either configuration or code?

There are a few and that's the reason I asked if there's anything that could affect the plugin other than the missing binaries or misconfiguration. 

About your other questions, no we have not added any rewrites. No other changes in the configuration except that we changed the location of the container, the rootUrl in the the code below.
I wonder though why the back office could not retrieve the images when it was able to put it in the specified container.

```
<?xml version="1.0"?>
<FileSystemProviders>
  
  <!-- Media -->
  <Provider alias="media" type="Our.Umbraco.FileSystemProviders.Azure.AzureBlobFileSystem, Our.Umbraco.FileSystemProviders.Azure">
  	<Parameters>
  		<add key="containerName" value="media"/>
  		<add key="rootUrl" value="https://***.blob.core.windows.net/"/>
  		<add key="connectionString" value="DefaultEndpointsProtocol=https;AccountName=***;AccountKey=***"/>
  		
  		<add key="maxDays" value="365"/>
  	</Parameters>
  </Provider>
   
</FileSystemProviders>
```

>  I'm wondering if your VirtualPathProvider setting have been changed or removed.

We never had it configured.

**Comment by JimBobSquarePants** [comment]
So you changed the physical location of the blob storage container?

>We never had it configured.

When the plugin is installed, by default, VirtualPathProvider configuration is added to the web.config file. I've written about in the readme here. 

https://github.com/JimBobSquarePants/UmbracoFileSystemProviders.Azure#virtual-path-provider

What happens when you open the images in a new tab or with caching disabled in the browser? What's the response code?

This ensures that all paths are stored in the Umbraco db as relative paths stemming from the "/media" root, if that provider is not set then the absolute url is used instead.

**Comment by vonbv** [comment]
> So you changed the physical location of the blob storage container?

Yes, since we switched from one Azure account to another.

> When the plugin is installed, by default, VirtualPathProvider configuration is added to the web.config file. 

Right, sorry about that, so we have it and is configured the same since it was installed, similar to the ReadMe.

> What happens when you open the images in a new tab or with caching disabled in the browser? What's the response code?

Please see attached image. Does that help?
![getbyid](https://cloud.githubusercontent.com/assets/870921/15006001/313d8d66-11fe-11e6-892d-4ce85fa19b88.png)

**Comment by JimBobSquarePants** [comment]
Sorry, I meant right-click on where the image would be on the page and open it in new tab. Let's see what happens you do that. I'm keen to see if we get a 404 or a 500. 

I've a feeling we'll have to attach a debugger eventually.

**Comment by vonbv** [comment]
Hi Jim, sorry for the late reply. It's weird I did not get notification on your reply and I was waiting for it. So I tried right clicking it and the image opened in the new tab and got the same issue - blank image
![blank_image](https://cloud.githubusercontent.com/assets/870921/15059239/d299b256-1353-11e6-8081-9eca0d346300.png)

**Comment by vonbv** [comment]
One more thing I noticed is that the folder Id that is saved in the container is not the same as the folder Id that is in the back-office. Please see attached screenshot. You will notice that in Umbraco the Id of the image is "1288" but in the storage it's "1136". That is a new upload I tested so I'm sure that's the only file with that name in the container. That is backed up by the time stamp I highlighted in the image.

![diff_in_filename](https://cloud.githubusercontent.com/assets/870921/15061155/86568296-1364-11e6-8c90-cccedfcf6e89.png)

**Comment by JimBobSquarePants** [comment]
The id's will actually be correct. The folder id is separate from the image id (it's confusing I know but they store both the image and a thumbnail in there) 

What was the response from the server when you opened the image in a new tab, you'll be able to see this in your development tools.

**Comment by vonbv** [comment]
You might notice the Id I'm giving you is different. It's another newly uploaded image as I deleted the old ones already.

![blob_response](https://cloud.githubusercontent.com/assets/870921/15061500/df2306f2-1368-11e6-9496-51cc62909379.png)
![blob_response2](https://cloud.githubusercontent.com/assets/870921/15061501/df2ca586-1368-11e6-8150-9b72c02f50ba.png)

**Comment by vonbv** [comment]
Upon further investigation. I noticed that the issue could be because the "cache" container stopped working. So there is the "media" and "cache" containers in our Storage account. The media is being updated as I've shown in screen shots from my previous comments. But the cache is not as I can see the "last modified" date is way too old, from last year. I checked the cached items and there's no entry for this month. Is it the plugins job to add the cached items?
![storage](https://cloud.githubusercontent.com/assets/870921/15061589/a3f3298a-1369-11e6-882b-8aaaf469b908.png)

**Comment by JimBobSquarePants** [comment]
The cache directory is created by the ImageProcessor Azure Cache plugin. I would check your setting in there to ensure everything is up to date.

**Comment by vonbv** [comment]
That was it! I've forgotten about that settings. Thank you so much for being very responsive. You rock!

**Comment by JimBobSquarePants** [comment]
Ah brilliant!! So glad we got to the end of it. Teamwork FTW! :smile:
