### ISSUE TITLE
Site in application directory breaking images

### ISSUE THREAD

**Issue by idontbyte** [JimBobSquarePants/UmbracoFileSystemProviders.Azure#43]
Hi,
I have a site running inside of an application directory e.g.
www.domain.com/appdirectory/umbraco/
I have resized images displaying perfecly, however if you try to view an image straight from the /media directory it does not display.
Is there any configuration I can change or is this a bug?
Cheers,
Jamie

--

**Comment by JimBobSquarePants** [comment]
Hi Jamie, 

So Umbraco is running inside a subdirectory? Hmmm truth be told I don't actually know. I couldn't find any documentation on running Umbraco in a subdirectory. @Jeavon Have you faced this before?

**Comment by idontbyte** [comment]
yeah, I had to change the ImageProcessor cache option so that the 'prefix' becomes subdirectory/media instead of media but now that works, so all resized images are displaying fine, it's just directly linking to images in the media folder that doesn't work, they return a 404. 

I'm going to start debugging today by putting the UmbracoFileSystemProviders.Azure in to my project and see whether any of the code is being hit at all.

**Comment by Jeavon** [comment]
I'm not sure how a VPP behaves with being a virtual application, it's probably registering at the root level?

**Comment by idontbyte** [comment]
I think this could be it... (see image)
<img width="565" alt="screenshot 2016-05-06 11 29 29" src="https://cloud.githubusercontent.com/assets/8790123/15070714/f4428372-137d-11e6-92e7-1a244bf13049.png">

**Comment by idontbyte** [comment]
Well I did some debugging and the VPP is returning file exists after going off and checking blob storage but the file is still returning 404..

**Comment by idontbyte** [comment]
Another Virtual Directory problem - Uploaded images do not retain the virtual directory path unlike normal Umbraco uploads, e.g.
Image uploaded without azure = /virtual/media/image.jpg
Image uploaded with azure = /media/image.jpg
This means that they can never be viewed.

**Comment by JimBobSquarePants** [comment]
@idontbyte I think there might be something funky you have to do to ensure that config files inherit. Something to do with this variable maybe? 

https://msdn.microsoft.com/en-us/library/system.configuration.sectioninformation.inheritinchildapplications%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396

I've zero experience on the subject I'm afraid. I've only ever run we application from the root directory.

**Comment by idontbyte** [comment]
Hi,
After much research I discovered that _microsoft_ don't seem to support VPP's in Virtual Directories very well and it causes all sorts of mayhem.
I think we can close this now, I don't think there's anything wrong with your code at all with respect to virtual directories, if it worked in .NET then it would work fine.
Cheers,
Jamie

**Comment by JimBobSquarePants** [comment]
Thanks for that. I was stumped! :smile:
