### ISSUE TITLE
Overriding configuration in Azure Portal

### ISSUE THREAD

**Issue by 0xc0dec** [JimBobSquarePants/UmbracoFileSystemProviders.Azure#44]
Hi,

Currently as I see it the module is configured via the `Config/FileSystemProviders.config` file. This forces me to store my storage credentials in a repo, also making it difficult to keep different credentials in different branches (ex. staging vs. production) during merge.

Is it possible to somehow configure the module via the `appSettings` section? This would allow me to remove sensitive info from the repo and override it in the Azure Management Portal.

Maybe it's more a Umbraco-specific question, but I couldn't find an answer to it so far. Thanks.

**Comment by JimBobSquarePants** [comment]
Hi,

The configuration follows the process that Umbraco uses and we cannot change that just now I'm afraid. Until they provide a means I cannot. 

Cheers

James
