### ISSUE TITLE
Files deployed by Courier end up on target system local file system

### ISSUE THREAD

**Issue by geoffbeaumont** [JimBobSquarePants/UmbracoFileSystemProviders.Azure#45]
Media deployed using Courier finishes up on the local file system of the target system rather than in the Azure Blob Storage container.

Bug logged against Courier here:
http://issues.umbraco.org/issue/COU-204

Raising it here as HQ seem to be blaming it on file system providers rather than Courier on the Our Umbraco form, here:
https://our.umbraco.org/forum/umbraco-pro/courier/71072-courier-doesnt-copy-media-with-relation

However - it's affecting multiple file system providers, and I can't find any information about anything Courier specific that file system providers are supposed to implement, so I think this is most likely Courier bypassing the file system provider, despite the claim that it passes everything off to the core system. They do claim that the old Azure Blob Storage Provider (https://our.umbraco.org/projects/backoffice-extensions/azure-blob-storage-provider/) did work correctly with Courier, but I'm not able to verify this.

**Comment by JimBobSquarePants** [comment]
@geoffbeaumont Hmm... All we do is implement the `IFileSystem` api. 

You can see the Add method here.

https://github.com/JimBobSquarePants/UmbracoFileSystemProviders.Azure/blob/b0428bbbd2c276e5d8d19e1c8584487cae5f33de/src/UmbracoFileSystemProviders.Azure/AzureFileSystem.cs#L190

At no point do we ever touch the file system, always working with the Azure API so there is no way we can be responsible for saving the media. 

I am not convinced the original Azure provider worked nor that Courier is using the proper provider.

**Comment by oooshola** [comment]
I'm getting the same issue with the latest 0.5.3 version and umbraco 7.4.3 and courier 2.52.13. However, pushing from stage > live superfluously creates the file in both live's media folder and in the blob storage container. Not sure what to do, but at least it's being saved in the right place.

**Comment by oooshola** [comment]
@JimBobSquarePants  I do agree though, that this is either a Courier or Umbraco core issue. The issue only happens when courier is involved.

**Comment by JimBobSquarePants** [comment]
Thanks @oooshola  I'm gonna close this now as I'm convinced it's not us.
