### ISSUE TITLE
GetFiles shouldn't return a list of null

### ISSUE THREAD

**Issue by nul800sebastiaan** [JimBobSquarePants/UmbracoFileSystemProviders.Azure#50]
Re: https://github.com/JimBobSquarePants/UmbracoFileSystemProviders.Azure/blob/develop/src/UmbracoFileSystemProviders.Azure/AzureFileSystem.cs#L440

When you ask for files in a folder and filter them, currently it will return an `IEnumerable<string>` with just nulls in the list.. To me that's a very awkward result. So, suppose I have a 100 files in the blob, all ending with `.jpg` and I ask for: `var allGifs = GetFiles("myfolder", "*.gif")` - I would expect to be able to go `if(allGifs.Any) { } `. However, that will not work, I get a 100 items, all null.

Can we change this to:

```
                    return null;
                }).Where(x => x != null);
```

Otherwise I'd have to add this Where clause to all the code I'm writing that calls into this method.

I'll send a PR with this change now.,

**Comment by JimBobSquarePants** [comment]
Merged. Thanks!
