### ISSUE TITLE
Allow for multiple UmbracoFileSystemProviders.Azure instances

### ISSUE THREAD

**Issue by nul800sebastiaan** [JimBobSquarePants/UmbracoFileSystemProviders.Azure#52]
Following up on this comment in the discussion: 
https://our.umbraco.org/forum/using-umbraco-and-getting-started/77175-why-cant-i-have-multiple-umbracofilesystemprovidersazure-instances#comment-247556

**Comment by Jeavon** [comment]
Also some discussion here https://github.com/JimBobSquarePants/UmbracoFileSystemProviders.Azure/pull/48

**Comment by nul800sebastiaan** [comment]
Cool, working on a PR now.

**Comment by JimBobSquarePants** [comment]
Ooh nice! Looking forward to digging through your code for this. Terrible oversight on my part.

**Comment by JimBobSquarePants** [comment]
Merged and completed. Cheers!
