### ISSUE TITLE
CreateContainer gives error when passed in string isn't lower case

### ISSUE THREAD

**Issue by nul800sebastiaan** [JimBobSquarePants/UmbracoFileSystemProviders.Azure#54]
You can only make containers in lowercase apparently.

Will check if there's other rules and see if we can sanitize the input a little more then just `.ToLowerInvariant()`

**Comment by nul800sebastiaan** [comment]
From: https://msdn.microsoft.com/en-us/library/azure/dd135715.aspx

>1. Container names must start with a letter or number, and can contain only letters, numbers, and the dash (-) character.
2. Every dash (-) character must be immediately preceded and followed by a letter or number; consecutive dashes are not permitted in container names.
3. All letters in a container name must be lowercase.
4. Container names must be from 3 through 63 characters long.

I think sanitizing by just lowercasing the name is enough, the rest of the rules should make `CreateContainer` fail. Maybe a custom YSOD linking to the page above?

**Comment by JimBobSquarePants** [comment]
@nul800sebastiaan I will get round to this I promise.

**Comment by JimBobSquarePants** [comment]
Merged and fixed. Thanks!
