### ISSUE TITLE
Images are showing from Umbraco Backend but not in my pages

### ISSUE THREAD

**Issue by jezguitarist30** [JimBobSquarePants/UmbracoFileSystemProviders.Azure#57]
Hi I recently upgraded the old UmbracoFileSystemProviders since @idseefeld recommend this new one but I'm encountering some problem.

I'm also using Microsoft.WindowsAzure.Storage and Configuration for me to grab the images and put it in a stream but that's a another story since I think I've already fixed the compatibility issue with this.

going back to my main problem now, in my Media section in Umbraco backend all the images are showing even in the contents section where I used a media picker but for some strange reason it is not showing when I view the actual page.  Please help me I've been stuck in this for 2days now.

**Comment by JimBobSquarePants** [comment]
Hi there,

Could you please share your details so that we can debug. It's quite impossible to do so without them.

- Version numbers (Umbraco, This Plugin, ImageProcessor.Web)
- Config files 

> I'm also using Microsoft.WindowsAzure.Storage and Configuration for me to grab the images and put it in a stream but that's a another story since I think I've already fixed the compatibility issue with this.

What do you mean by this? The images are supposed to be served using the CloudImageService from ImageProcessor.Web

Cheers

James

**Comment by jezguitarist30** [comment]
I just upgraded my Umbraco to version 7.5 and downloaded UmbracoFileSystemProviders.Azure_0.5.3-beta, ImageProcessor.Web v4.6.4.0

FileSystemProviders.config
`<?xml version="1.0"?>
<FileSystemProviders>
  <Provider alias="media" type="Our.Umbraco.FileSystemProviders.Azure.AzureBlobFileSystem, Our.Umbraco.FileSystemProviders.Azure">
  	<Parameters>
  		<add key="containerName" value="media"/>
  		<add key="rootUrl" value="http://wisewebstorage.blob.core.windows.net/"/>
  		<add key="connectionString" value="DefaultEndpointsProtocol=https;AccountName=xxxxxxx;AccountKey=xxxxxx"/>
  		<add key="maxDays" value="365"/>  
  		<add key="useDefaultRoute" value="true"/>
  	</Parameters>
  </Provider>
</FileSystemProviders>`


security.config
`<?xml version="1.0" encoding="utf-8"?>
<security>
  <services>
    <service name="LocalFileImageService" type="ImageProcessor.Web.Services.LocalFileImageService, ImageProcessor.Web" />
    
    
    <service prefix="remote.axd" name="RemoteImageService" type="ImageProcessor.Web.Services.RemoteImageService, ImageProcessor.Web">
      <settings>
        <setting key="MaxBytes" value="4194304" />
        <setting key="Timeout" value="3000" />
        <setting key="Protocol" value="http" />
      </settings>
      <whitelist>
      </whitelist>
    </service>
    <service prefix="media/" name="CloudImageService" type="ImageProcessor.Web.Services.CloudImageService, ImageProcessor.Web">
      <settings>
        <setting key="Container" value=""/>
        <setting key="MaxBytes" value="8194304"/>
        <setting key="Timeout" value="30000"/>
        <setting key="Host" value="http://wisewebstorage.blob.core.windows.net/media/"/>
      </settings>
    </service>
  </services>
</security>`


In backend all media are showing but on the pages they don't, everything is working fine before I updated Umbraco to v7.5 and downloaded the latest UmbracoFileSystemProviders.Azure package.

**Comment by JimBobSquarePants** [comment]
Thanks for the additional info. I think mentioning the Umbraco upgrade should have been first off the bat :wink: 

First off, can you edit your CloudImageService config to match the following?

``` xml
    <service prefix="media/" name="CloudImageService" type="ImageProcessor.Web.Services.CloudImageService, ImageProcessor.Web">
      <settings>
        <setting key="Container" value="media"/>
        <setting key="MaxBytes" value="8194304"/>
        <setting key="Timeout" value="30000"/>
        <setting key="Host" value="http://wisewebstorage.blob.core.windows.net/media"/>
      </settings>
    </service>
```

Now... Umbraco has a change in 7.5.0 which could affect the virtual path provider 

http://issues.umbraco.org/issue/U4-8472

Can you check to see if you have a web.config file in your media directory and check inside it.

There is most likely the line 
``` xml
<add name="StaticFile" path="*" verb="*" modules="StaticFileModule,DefaultDocumentModule,DirectoryListingModule" resourceType="Either" requireAccess="Read" />
```

If all this is there can you add the following line just before it.

``` xml
<add name="StaticFileHandler" path="*" verb="*" preCondition="integratedMode" type="System.Web.StaticFileHandler" />
```

That should hopefully get everything working again.

**Comment by jezguitarist30** [comment]
Wow!! that really did the trick! :+1:  I'm very happy thanks for helping me out.

just quick question though, do you know any compatibility issue with WindowsAzure.Storage and Microsoft.WindowsAzure.ConfigurationManager I'm currently using them in my C# code to grab some files from Azure blob storage? I'm getting error earlier not sure if I wasn't able to install UmbracoFileSystemProviders.Azure package correctly or it's a compatibility issue.

**Comment by JimBobSquarePants** [comment]
Thats great news!

Not off the top of my head I'm afraid, maybe a Nuget versioning issue? All the code in the UmbracoFileSystemProviders.Azure package just uses the Azure API, nothing fancy

**Comment by leethomascook** [comment]
That web config change in media folder broke it for me as well on Umbraco 7.5. Thanks for the fix!

**Comment by jayantrajwani** [comment]
I am working on an existing umbraco project. It is not allowing me to upload any files to media. Though it is showing me the images in media on backend but it is not loading them on the site.
![image](https://user-images.githubusercontent.com/11351528/35214541-81b7b000-ff87-11e7-82ad-e410dba13e93.png)
![image](https://user-images.githubusercontent.com/11351528/35214709-0f1a56e6-ff88-11e7-827d-de96b4131802.png)

Any help would be greatly appreciated. Thanks!

**Comment by jayantrajwani** [comment]
I'm extremely sorry i just thought that you have closed this issue so might not see my comment here so posted it as another issue. Thanks for your response.
