### ISSUE TITLE
Move connection string into web.config

### ISSUE THREAD

**Issue by jasonshsoftware** [JimBobSquarePants/UmbracoFileSystemProviders.Azure#58]
If you move the connection string from the FileSystemProviders.config to the web.config, it will remove the need for the AzureBlobFileSystem.UseStorageEmulator flag.

It will also allow me to keep it as UseDevelopmentStorage=true for my development, as well as what is checked into source control. Then, I can just override it in my Azure website Application Settings blade in the portal. That way, my storage account key never makes it into source control.

Keeping it in FileSystemProviders.config affords me no flexibility to change it at runtime within an azure website.

**Comment by JimBobSquarePants** [comment]
Hi there,

I'm assuming you didn't read existing issues and PR's?

https://github.com/JimBobSquarePants/UmbracoFileSystemProviders.Azure/pull/28

Coming in v0.5.4

Cheers

James
