### ISSUE TITLE
Installing 0.5.4 in Umbraco 7.5.2

### ISSUE THREAD

**Issue by hnky** [JimBobSquarePants/UmbracoFileSystemProviders.Azure#59]
When installing the nuget package i get the following error: 

Install-Package : Unable to find a version of 'Lucene.Net' that is compatible with 'Examine 2.0.0-beta2 constraint: Lucene.Net (>= 3.0.3)', 'Lucene.Net.Contrib 3.0.3-RC2 constraint: Lucene.Net (>= 3.0.3-RC2)', 'UmbracoCms.Core 7.5.2 constraint: Lucene.Net (>=
 2.9.4.1 && < 3.0.0)'.

**Comment by JimBobSquarePants** [comment]
We don't reference either of those libraries. If there's an issue then it's something else I'm afraid probably something to do with your dependency rules in the Nuget setup. Is it set to lowest?

https://www.nuget.org/packages/UmbracoFileSystemProviders.Azure/
