### ISSUE TITLE
Images are not served from the cache

### ISSUE THREAD

**Issue by vonbv** [JimBobSquarePants/UmbracoFileSystemProviders.Azure#60]
We have been using version 0.5.3 without any issues until a few days ago. Some and not all images are served from the CDN some are not. I have upgraded to 0.5.5 and still encounters the same issue. Has anyone else encountered the same? I checked all settings in FileSystemProviders, cache and security config files and nothing changed. All are pointing to the correct cdn root and using the correct storage and cdn accounts. Anybody who has an idea what could cause the recent issue we're encountering?

**Comment by JimBobSquarePants** [comment]
The IFileSystemProvider doesn't serve images from the CDN, it serves them from BlobStorage. 

You're probably hitting a timeout in the ImageProcessor.Web AzureBlobCache. If the request times out it will revert to serving from blob storage.
