### ISSUE TITLE
VPP prevents videos being served to Safari

### ISSUE THREAD

**Issue by Jeavon** [JimBobSquarePants/UmbracoFileSystemProviders.Azure#61]
I'm pretty sure this is for the same reason as described in this blog post about EpiServer http://www.markeverard.com/2011/07/05/serving-videos-to-ios-devices-from-episerver-vpp-folders/

**Comment by JimBobSquarePants** [comment]
Interesting. I think I've heard of this before. Will have a good look at the source for that fix and see what we can do. The fix they've coded seems to throw another error.

**Comment by JimBobSquarePants** [comment]
I think we'll have to set the appropriate headers here. 

https://github.com/JimBobSquarePants/UmbracoFileSystemProviders.Azure/blob/fcd720f503fcdf31a5b9c7bdd0cbe891e7178f7e/src/UmbracoFileSystemProviders.Azure/FileSystemVirtualFile.cs#L74

The base class referenced in the Scott Mitchell article is the same as this one here. Fingers crossed we can read the request headers and communicate the necessary info to blob storage which already supports range-specific requests. 

https://github.com/markeverard/FortuneCookie.RangeRequestFileHandler/blob/beaebd660f4f0fe316334724df869154bdc7e810/src/FortuneCookie.RangeRequestFileHandler/RangeRequestHandlerBase.cs

**Comment by kevinduong** [comment]
I'm having this issue only with Safari 10. The videos load on Safari 8.

**Comment by JimBobSquarePants** [comment]
>I'm having this issue only with Safari 10. The videos load on Safari 8.

Needs to be fixed either way. Still looking for assistance on this as I don't have the equipment to test.

**Comment by kevinduong** [comment]
Submitted a pull request for this issue. Tested it on Mac OS X 10.12.1 and Safari 10.0.01. PR #75

**Comment by JimBobSquarePants** [comment]
If that's how simple the fix is my mind is blown. I thought we have to copy the headers from Azure.

**Comment by kevinduong** [comment]
@JimBobSquarePants when is 0.5.9 going to be in beta and released?

**Comment by PezCo** [comment]
Any news on this? or a work around until release?

**Comment by kevinduong** [comment]
@PezCo If you really really need to, you could just pull down my fork and use that for now.

**Comment by Jeavon** [comment]
There is already fix for this included in the current MyGet version https://www.myget.org/gallery/umbracofilesystemproviders-azure

**Comment by JimBobSquarePants** [comment]
@Jeavon Anything stopping us pushing that to Nuget? I can't think of anything.

**Comment by Jeavon** [comment]
@JimBobSquarePants yes I think tomorrow might warrant the final beta release with RTM to follow in a couple of weeks! Woohoo!

**Comment by JimBobSquarePants** [comment]
Yaaaas! I'll let you push the button on that one. I'm a bit swamped just now.

**Comment by Jeavon** [comment]
Fixed in v0.5.9
