### ISSUE TITLE
Setting: AzureBlobFileSystem.UsePrivateContainer in web.config doesn't work

### ISSUE THREAD

**Issue by hnky** [JimBobSquarePants/UmbracoFileSystemProviders.Azure#72]
If you use this setting in the web.config:
add key="AzureBlobFileSystem.UsePrivateContainer" value="false" 

The blob is always marked private.

**Comment by JimBobSquarePants** [comment]
I don't understand. Could you fill in the issue properly.

**Comment by hnky** [comment]
I see the layout of the issue got messed up.

I mean this setting in the web.config.
add key="AzureBlobFileSystem.UsePrivateContainer" value="false"

**Comment by Jeavon** [comment]
I did notice a small mistake in the readme which I've now corrected, maybe it's this:

<add key="AzureBlobFileSystem.UsePrivateContainer" value="false" />

should be 

<add key="AzureBlobFileSystem.UsePrivateContainer:media" value="false" />

@hnky which do you have?

**Comment by Jeavon** [comment]
@hnky oh you already posted it (just lost it's formatting on email), but yes looks like you need to add the ":media" to your key
