### ISSUE TITLE
Feature request - Some kind of backup system

### ISSUE THREAD

**Issue by SteveVaneeckhout** [JimBobSquarePants/UmbracoFileSystemProviders.Azure#76]
We started using Azure for all our new Umbraco sites but one of the problems we're facing is the lack of a automatic backup system for an Azure storage account. Azure provides lots of redundancy options but it doesn't prevent customers from _"accidentally"_ deleting media.
I had 2 ideas to solve this problem:

- Create an Azure function that creates a copy of the whole media container every day.
- Add a feature to this FileSystemProvider to move a file to a private backup container whenever a user deletes a file. The user sees the file is gone but we can still restore it.

The second solution seems to be the most elegant as it doesn't waste so much space, yet no files will be lost.

Before I try to implement this feature I would like to hear someone else's opinion. Am I on the right track or is there something I'm missing?

**Comment by JimBobSquarePants** [comment]
Hi @SteveVaneeckhout 

I think that functionality is out of the scope of the project. There's nothing to stop you deleting the media with the standard Umbraco `PhysicalFileSystem`.  I don't think it would be wise to overcomplicate things.

https://github.com/umbraco/Umbraco-CMS/blob/62af834176149e5980c9aa9a9e5daf158ca65f99/src/Umbraco.Core/IO/PhysicalFileSystem.cs#L163

What do you think @Jeavon 

Cheers

James

**Comment by caterwomtious** [comment]
I agree it feels like a separate problem - it's just backing up blob storage, regardless of the fact that it's Umbraco content in there.

I'm using more-or-less the first suggested approach to do this - a daily web job that kicks off AZCopy.exe, then the files are picked up by Azure's standard web app backup. The destination could actually be anywhere but I'm just using /media because it's convenient.

```
AzCopy /Source:https://my-account.blob.core.windows.net/media /Dest:d:\home\site\wwwroot\media /SourceKey:my-account-key /S /Y
```

**Comment by Jeavon** [comment]
There is a comprehensive blob post and accompanying GitHub repo about how to use AzCopy on a schedule with a WebJob http://markjbrown.com/azure-webjobs-azcopy/ & https://github.com/markjbrown/AzCopyBackup

I'm amazed someone hasn't wrapped this up into a Azure Service in the Marketplace, seems like something people would use a fair bit

**Comment by Jeavon** [comment]
FYI, I recently found https://www.cherrysafe.com which offers a storage account sync feature and has a "Snapshot files before overwriting" feature which in effect gives you PIT backup

**Comment by gavinfaux** [comment]
Another FYI -  [Azure Data Factory Copy Activity](https://docs.microsoft.com/en-us/azure/data-factory/copy-activity-overview) can be used to copy between blob storage accounts; also allows triggers (e.g. daily  task). Blob storage [throughput is 1.0 GBps](https://docs.microsoft.com/en-us/azure/data-factory/copy-activity-performance), so very fast. 

Expressions / functions can be used for setting dynamic variables such as dates in folder paths - we currently don't do this which means a restore could copy back media that was deleted legitimately.

We have had to restore once from the copy when a mishap led to deletion of main media storage (> 1.5GB).
