### ISSUE TITLE
OK for StaticFileHandler defined in both web.config and media/web.config?

### ISSUE THREAD

**Issue by somoreingold** [JimBobSquarePants/UmbracoFileSystemProviders.Azure#77]
Hello,

Great plugin! I'm using Umbraco 7.5.13 and version 0.5.7beta. I just installed it, and went through the wizard steps. It automatically added the StaticFileHandler configuration described here: https://github.com/JimBobSquarePants/UmbracoFileSystemProviders.Azure#virtual-path-provider  However, it added it in **both** places. Your wording says "For Umbraco v7.5+ you must add the the StaticFileHandler to the new Web.config inside the Media folder **_instead_** of the root one or the VPP will not work!"

My question is, How strict is "instead" in your phrasing? Is it ok if I have the web.config definition AND the media/web.config definition? Because that's what your package writes during installation. I just want to make sure nothing breaks if both are present.

Thanks!

**Comment by Jeavon** [comment]
It's fine to have it in both. Thinking about it now, I can't remember why I wrote "instead", I do remember being very happy when I found out the new media web.config was the issue with 7.5...

**Comment by somoreingold** [comment]
WOW....laser fast response! Thanks Jeavon!
