### ISSUE TITLE
Impossible to modify or delete content with images on umbraco

### ISSUE THREAD

**Issue by arlan85** [JimBobSquarePants/UmbracoFileSystemProviders.Azure#79]
I have a serious issue with my site after change our image storage to Azure blob, when I tried to delete it I get this error 
![reese](https://cloud.githubusercontent.com/assets/9948111/25970436/a5824634-3666-11e7-9e76-4ea1cd9c80ec.png)

Error list on logs
```

2017-05-11 17:10:05,271 [P1012/D3/T40] ERROR ImageProcessor.Web.HttpModules.ImageProcessingModule - 
ImageProcessor.Common.Exceptions.ImageProcessingException: ProcessImageAsync 597 : No image exists at D:\home\site\wwwroot\media\126812\bob400x600.jpg
 2017-05-11 17:12:17,573 [P1012/D3/T23] ERROR ImageProcessor.Web.HttpModules.ImageProcessingModule - 
ImageProcessor.Common.Exceptions.ImageProcessingException: ProcessImageAsync 597 : No image exists at D:\home\site\wwwroot\media\126803\constance-659x420.jpg
 2017-05-11 17:14:25,462 [P1012/D3/T14] ERROR ImageProcessor.Web.HttpModules.ImageProcessingModule - 
ImageProcessor.Common.Exceptions.ImageProcessingException: ProcessImageAsync 597 : No image exists at D:\home\site\wwwroot\media\126805\vietna.jpg
 2017-05-11 17:14:52,993 [P1012/D3/T39] ERROR ImageProcessor.Web.HttpModules.ImageProcessingModule - 
ImageProcessor.Common.Exceptions.ImageProcessingException: ProcessImageAsync 597 : No image exists at D:\home\site\wwwroot\media\126811\cuda-659x420.jpg
 2017-05-11 17:15:19,981 [P1012/D3/T8] ERROR ImageProcessor.Web.HttpModules.ImageProcessingModule - ImageProcessor.Common.Exceptions.ImageProcessingException: ProcessImageAsync 597 : No image exists at D:\home\site\wwwroot\media\126810\where.jpg

```
This images are inside a Custom mediatype but it was working until I move it to another folder in the website structure. Now i can do anything with it, I can't delete it, change or move it. 
Could be this this module configuration problem?

**Comment by JimBobSquarePants** [comment]
Can you double check you have the VPP config setup correctly in your media folder. See tue readme for specifics.

**Comment by arlan85** [comment]
Hi, I have ~/Config/FileSystemProviders.config

` <Provider alias="media" type="Our.Umbraco.FileSystemProviders.Azure.AzureBlobFileSystem, Our.Umbraco.FileSystemProviders.Azure">
    <Parameters>
      <add key="containerName" value="container"/>
      <add key="rootUrl" value="http://[my-blob].blob.core.windows.net/"/>
      <add key="connectionString" value="DefaultEndpointsProtocol=https;AccountName=[my-blob];AccountKey=[mykey];"/>
      


      
      <add key="maxDays" value="365"/>
      <add key="useDefaultRoute" value="true"/>
    </Parameters>
  </Provider>`

and in ~/media/Web.config
`<?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <system.webServer>
    <handlers>
      <clear />
      <add name="StaticFileHandler" path="*" verb="*" preCondition="integratedMode" type="System.Web.StaticFileHandler" />
      <add name="StaticFile" path="*" verb="*" modules="StaticFileModule,DefaultDocumentModule,DirectoryListingModule" resourceType="Either" requireAccess="Read" />
    </handlers>
  </system.webServer>
</configuration>`

It is anything else required? When I create a new items the new ones wroks fine but the old ones, I can do anything with those.

**Comment by JimBobSquarePants** [comment]
Are you using the `CloudImageService?` configured to intercept the media folder? ImageProcessor should not be requesting local files.
