### ISSUE TITLE
Problems with WindowsAzure.Storage dependency having intalled ImageProcessor.Web.Plugins.AzureBlobCache

### ISSUE THREAD

**Issue by teeto** [JimBobSquarePants/UmbracoFileSystemProviders.Azure#80]
I have been using UmbracoFileSystemProviders.Azure for a while without problems. But installing ImageProcessor.Web.Plugins.AzureBlobCache i have this error when using AzureBlobCache:

`No se puede cargar el archivo o ensamblado 'Microsoft.WindowsAzure.Storage, Version=4.3.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' ni una de sus dependencias. La definición del manifiesto del ensamblado no coincide con la referencia al ensamblado. (Excepción de HRESULT: 0x80131040)`

I have the 6.3.0 version from UmbracoFileSystemProviders.Azure, but the AzureBlobCache seems to look for v4.3.0. If i set cache to DiskCache, everythink works.
Note that i have installed AzureBlobCache manually as using nuget updates a lot of things and my project didnt work out.

**Comment by JimBobSquarePants** [comment]
What about using Assembly binding redirects? Did you give that a try?

**Comment by teeto** [comment]
Thanks Jim, i had never used assembly redirect. Now it works, adding this to my web.config:

```
<dependentAssembly> 
      <assemblyIdentity name="Microsoft.WindowsAzure.Storage" publicKeyToken="31bf3856ad364e35" culture="neutral" /> 
    <bindingRedirect oldVersion="4.3.0.0" newVersion="6.2.0.0" /> 
    </dependentAssembly>
```
I though it would do an automatic binding as i am using a newer version.
I installed the provider using the Umbraco package installer. This was on an Umbraco site installed without nuget. So when trying to install de cache plugin using nuget it updated a lot of packages like Newtonsoft.Json, Umbraco.Core (a version older than mine), etc and it messed my project. So i copied configurations and dlls from other projects that were using the azure cache plugin.

**Comment by JimBobSquarePants** [comment]
Glad you got it sorted. 😄 

Nuget is always the best way to install update Umbraco etc. It takes a bit of work converting a non-Nuget install but it's definitely worth the effort.
