### ISSUE TITLE
Stable nuget release coming any time soon?

### ISSUE THREAD

**Issue by markwemekamp** [JimBobSquarePants/UmbracoFileSystemProviders.Azure#86]
Hi!
First of all thanks for the awesome package.
I was wondering if there will be a stable release of nuget package coming anytime soon? We would like to include it in the nuspec of a project (that we use for CD) but since it's flagged as pre-release we have to mark our project as pre-release as well. 

Kind regards,
Mark

**Comment by JimBobSquarePants** [comment]
@Jeavon We need to get on this. Have you any time to test the latest code base? 

Once we merge #82 and #84 and test everything I think we're probably stable enough to go 1.0.

**Comment by Jeavon** [comment]
@JimBobSquarePants I agree, but there are a fair number of unreleased changes already in the develop branch (VPP support, accept ranges & more) if we get #82 and #84 merged and tested, we should make one final beta release (to get widespread testing) and then go RTM shortly after IMO.

Can we ask the authors of #82 and #84 to test the MyGet once we've merged? I'm happy to do some overall testing but they are quite specific tweaks both about running Umbraco inside virtual folders...

**Comment by JimBobSquarePants** [comment]
@Jeavon   Ok, that sounds like a great plan. Thanks!

**Comment by JimBobSquarePants** [comment]
I think we can merge both. They look save to me.

**Comment by kevinduong** [comment]
Will there be any breaking changes in the next release?

**Comment by JimBobSquarePants** [comment]
No there shouldn't be. All good.

**Comment by fuzzzerd** [comment]
Is there a planned stable release? Looks like 0.5.10 came out several months ago.

**Comment by Jeavon** [comment]
Yes there is, probably tomorrow or at the latest on Wednesday

**Comment by Jeavon** [comment]
v1.0.0 has now been released! :confetti_ball: :tada:
