### ISSUE TITLE
Steps for migrating existing media

### ISSUE THREAD

**Issue by clarkd** [JimBobSquarePants/UmbracoFileSystemProviders.Azure#87]
Hi,

Could anyone share some steps/tutorial for migrating an existing site with existing media?

We have a fair bit of media and also other static content (outside of /media) that we'd like to move out of the Umbraco Cloud repositories. Deployments are way too slow right now!

Thanks,

Dave

**Comment by JimBobSquarePants** [comment]
Hi Dave,

As long as you were using the built in disk `IFileSystemProvider` this should be easy enough.

1. Grab yourself a copy of [Microsoft Azure Storage Explorer](http://storageexplorer.com/) 
2. Create a blob container called media
3. Drag you existing media folders into the blob container 

Though I thought Umbraco Cloud already used this no?

Cheers

James

**Comment by clarkd** [comment]
Hi James,

Thanks for the quick response - that worked a treat.

I'm a little confused with your comment about Umbraco Cloud - I don't think it's using it for media already? At least the default FileSystemProvider appears to be "Umbraco.Core.IO.PhysicalFileSystem". I'm not 100% sure though so if you're able to clarify that would certainly be appreciated.

Dave

**Comment by JimBobSquarePants** [comment]
Hi Dave, 

no worries, 

I'm surprised they're using the physical file system then. Adding media to the file system increases memory overheads due to file system watchers. 

Checking the config file in the config folder will give you clarity. 

Cheers

James
