### ISSUE TITLE
Can't access media files after upgrade to Umbraco 7.6.3

### ISSUE THREAD

**Issue by hakudoshi23** [JimBobSquarePants/UmbracoFileSystemProviders.Azure#89]
Hello,

We've been using this plugin on a site with Umbraco 7.5.11 for a few months and everything has been working great. Two days ago we upgraded to Umbraco 7.6.3 and now we can't access any media file, all the media URLs return 404.

There's no JS error in the page (apart from the 404) and also nothing in the log files.
We'll try to debug from the master branch to see if we find the issue.

This is our FileSystemProvider.config:

```
<?xml version="1.0"?>
<FileSystemProviders>
  <Provider alias="media" type="Our.Umbraco.FileSystemProviders.Azure.AzureBlobFileSystem, Our.Umbraco.FileSystemProviders.Azure">
  	<Parameters>
  		<add key="containerName" value="[name]"/>
  		<add key="rootUrl" value="https://[account].blob.core.windows.net/"/>
  		<add key="connectionString"
  			value="DefaultEndpointsProtocol=https;AccountName=[account];AccountKey=[key]"/>
  	</Parameters>
  </Provider>
</FileSystemProviders>
```

Has this plugin been tested with Umbraco 7.6.x?

Thanks!

**Comment by jstrugnell** [comment]
You can try adding the following additional parameter settings:

```
<!-- 
Optional configuration value determining the maximum number of days to cache items in the browser. Defaults to 365 days. 
-->
        <add key="maxDays" value="30"/>
<!--
        When true this allows the VirtualPathProvider to use the deafult "media" route prefix regardless 
        of the container name.
-->
        <add key="useDefaultRoute" value="true"/>
<!--
        When true blob containers will be private instead of public what means that you can't access the original blob file directly from its blob url.
-->
        <add key="usePrivateContainer" value="false"/>
```

**Comment by Jeavon** [comment]
I would say you have reverted the changes to the web.config found in the "Media" folder. See https://github.com/JimBobSquarePants/UmbracoFileSystemProviders.Azure#virtual-path-provider

**Comment by hakudoshi23** [comment]
Yes! It's working again.

It was the last suggestion. We didn't merge the web.config under the media folder correctly after the upgrade.

Thanks for the quick responses.
