### ISSUE TITLE
Using Azure Blob Storage with Examine  when Hosting In Azure App Service

### ISSUE THREAD

**Issue by brianmrush** [JimBobSquarePants/UmbracoFileSystemProviders.Azure#92]
I am having an issue with Examine when I use Azure Blog Storage.  Locally when I run the Azure Blob Storage works Great!   Thanks for this package.  The problem is when I publish out to an Azure App, I am getting an error reading the ExamineSettings.config file.    Can Azure Blob storage co exist with Examine in Azure?

Here is what I FileSystemProviders.config looks like

```
<?xml version="1.0"?>
<FileSystemProviders>
  <Provider alias="media" type="Our.Umbraco.FileSystemProviders.Azure.AzureBlobFileSystem, Our.Umbraco.FileSystemProviders.Azure">
    <Parameters>
      <add key="containerName" value="media" />
      <add key="rootUrl" value="https://images.openskycc.com/" />
      <add key="connectionString" value="DefaultEndpointsProtocol=http;AccountName=xxxxxxx;AccountKey=xxxxxxx;EndpointSuffix=core.windows.net"/>
      <add key="maxDays" value="365" />
      <add key="useDefaultRoute" value="true" />
      <add key="usePrivateContainer" value="false" />
    </Parameters>
  </Provider>
</FileSystemProviders>
```

And my ExamineSettings.config looks like this

```
<Examine>
  <ExamineIndexProviders>
    <providers>
      <add name="InternalIndexer" type="UmbracoExamine.UmbracoContentIndexer, UmbracoExamine"
          supportUnpublished="true"
          supportProtected="true"
           useTempStorage="Sync"
          analyzer="Lucene.Net.Analysis.WhitespaceAnalyzer, Lucene.Net"/>

      <add name="InternalMemberIndexer" type="UmbracoExamine.UmbracoMemberIndexer, UmbracoExamine"
           supportUnpublished="true"
           supportProtected="true"
           useTempStorage="Sync"
           analyzer="Lucene.Net.Analysis.Standard.StandardAnalyzer, Lucene.Net"/>

      --><!-- default external indexer, which excludes protected and unpublished pages--><!--
      <add name="ExternalIndexer" type="UmbracoExamine.UmbracoContentIndexer, UmbracoExamine"/>

    </providers>
  </ExamineIndexProviders>

  <ExamineSearchProviders defaultProvider="ExternalSearcher">
    <providers>
      <add name="InternalSearcher" type="UmbracoExamine.UmbracoExamineSearcher, UmbracoExamine"
           useTempStorage="Sync"
           analyzer="Lucene.Net.Analysis.WhitespaceAnalyzer, Lucene.Net"/>

      <add name="ExternalSearcher" type="UmbracoExamine.UmbracoExamineSearcher, UmbracoExamine" useTempStorage="Sync"/>

      <add name="InternalMemberSearcher" type="UmbracoExamine.UmbracoExamineSearcher, UmbracoExamine"
           useTempStorage="Sync"
           analyzer="Lucene.Net.Analysis.Standard.StandardAnalyzer, Lucene.Net" enableLeadingWildcard="true"/>

    </providers>
  </ExamineSearchProviders>

</Examine>



```

When I run locally, everything works great.  When I publish to azure I get the following error

```

An application error occurred on the server. The current custom error settings for this application prevent the details of the application error from being viewed remotely (for security reasons). It could, however, be viewed by browsers running on the local server machine.

Source File: D:\home\site\wwwroot\config\ExamineSettings.config    Line: 12 
```

If I switch my FileSystemProviders.config to this and publish to Azure that error goes away

```
<Provider alias="media" type="Umbraco.Core.IO.PhysicalFileSystem, Umbraco.Core">
      <Parameters>
        <add key="virtualRoot" value="~/media/" />
      </Parameters>
    </Provider>
```

Any insight is appreciated here.  I am having a hell of a time trying to store media in blob storage and getting Examine to work in Azure.  

Brian

**Comment by JimBobSquarePants** [comment]
Hi Brian,
I'd have to double check but your Examine settings don't look right to me. Both normally work perfectly together. 

Can you post the real reported error please, your error config needs to allow showing errors. 

Cheers

James

Also

**Comment by brianmrush** [comment]
James

You are correct.  When in doubt check the exception log!  I was an idiot
and did not read full exception.   The issue was that this dll was not
pushing out to the bin in azure
Our.Umbraco.FileSystemProviders.Azure.dll.  Once that published correctly
the issue went away.


The only thing I am seeing now is that if I try to publish a second time it
complains about examine indexes being locked.  That is obviously not
related to your dll but curious if you have seen something similar.  I
would hate to have to stop the app pool prior to publishing.


Thanks a alot for this DLL!  Also for getting back to me.

Brian

**Comment by JimBobSquarePants** [comment]
Happy to help! 😄 

Your Examine issues are probably being caused by the examine file location.

If you are running Examine 1.83+ you should use the temp directory for storage to prevent locking.

https://our.umbraco.org/Documentation/Getting-Started/Setup/Server-Setup/Load-Balancing/flexible#examine-v0-1-83

I'd recommend upgrading if you are not.
