### ISSUE TITLE
Original, uncropped version being returned

### ISSUE THREAD

**Issue by SChubb** [JimBobSquarePants/UmbracoFileSystemProviders.Azure#93]
Hi,

Really like the package and am using it alot.

Quick question for you though - under what circumstances can the original, uncropped image be returned? We seem to be having a number of issues when instead of the expected crop e.g. 
[http://ec2-54-72-91-84.eu-west-1.compute.amazonaws.com/media/2782/articles-7-quick-easy-tips-for-finding-and-booking-cheaper-flights.jpg?anchor=center&mode=crop&width=1200&height=450&rnd=131481627620000000](http://ec2-54-72-91-84.eu-west-1.compute.amazonaws.com/media/2782/articles-7-quick-easy-tips-for-finding-and-booking-cheaper-flights.jpg?anchor=center&mode=crop&width=1200&height=450&rnd=131481627620000000)

is returning the full-sized image rather than the requested crop.

Many thanks
Simon

**Comment by JimBobSquarePants** [comment]
Hi Simon,

This is nothing to do with the filesystemprovider. 

You'll be running out of contiguous memory when loading/resizing the image via ImageProcessor. Make sure your server is running in 64bit mode to handle large images. 

Cheers

James

**Comment by SChubb** [comment]
Hi James,

That doesn't seem to be the case I'm afraid. The server has 8GB of RAM is using a fairly steady 2GB. (image size is around 250KB) Even after deleting the cache folder to try and force an update I'm still being served back the original image. I've disabled caching in Chrome so should be hitting the server again. 

However, what I have noticed is that a new entry in the cache directory hasn't been created. IIS_IUSRS has full read/write permissions on that folder.

Any other reasons that might cause this I can explore?

Kind regards
Simon

**Comment by JimBobSquarePants** [comment]
Hi Simon,

It doesn't matter how much the server has if it's not running in 64bit mode. 32 bit can use up to 4gb ram but cannot utilize much contiguous space in that ram.

**Comment by JimBobSquarePants** [comment]
Hi Simon,

It doesn't matter how much ram the server has if the app pool is not running in 64bit mode. 32 bit can use up to 4gb ram but cannot utilize much contiguous space in that ram.

**Comment by SChubb** [comment]
Hi James,

Just checked and it's Windows Server 2016 running IIS 10, App Pool is 64 bit (as 32-bit applications is disabled). Definitely in 64-bit mode. 

Just wondering if there's any other error cases that might return the original image?

Cheers
Simon

**Comment by SChubb** [comment]
Hi,

OK, found the issue - it's not to do with 64-bit memory mode, it's to do with something we discussed previously about case-sensitive names due to using an AWS S3 store.

Basically, one of our CDN servers had the correct config to use our custom S3 file provider and the other one didn't.

Cheers
Simon

**Comment by JimBobSquarePants** [comment]
Ah @SChubb fantastic!

Really glad you found the issue. Any other issues or questions don't hesitate to ask.

Cheers

James
