### ISSUE TITLE
Azure Content-Range header & 206 status code not passed through

### ISSUE THREAD

**Issue by piemanji** [JimBobSquarePants/UmbracoFileSystemProviders.Azure#95]
I'm using this excellent plugin on my Umbraco website, but users have reported an issue affecting Safari (on desktop and mobile) where the audio controls don't appear in HTML5 audio elements. Instead, it says that it's a "Live Broadcast".

It seems that the cause of the issue is that when it comes through the virtual path provider, the audio file doesn't return the correct 206 status code, nor does it contain the correct Content-Range header (in fact, a lot of headers are discarded, but this is the one causing the issue I think). That doesn't cause an issue in other browsers, but Safari can't seem to handle it.

Here's an example:
Direct link - https://rotherhamec.blob.core.windows.net/media/1159/2017-09-24-no-other-gospel.mp3
Virtual path link - https://www.rotherham.ec/media/1159/2017-09-24-no-other-gospel.mp3

I tested this out using Fiddler. The second link has a 200 status code and no Content-Range header. Maybe it's something I'm just configuring incorrectly?

**Comment by hoest** [comment]
I have the same issue, no 206... +1

**Comment by idseefeld** [comment]
Hi,
just a quick coment. I guess it has to do with streaming capabilities of your webserver and nothing todoe with UmbracoFileSystemProviders.Azure. Actually there is no signifent difference between both URL's response headers. The different behavior results from diferent server configuration.

Quick research for IIS streaming setup lead me to https://docs.microsoft.com/en-us/iis/media/on-demand-smooth-streaming/getting-started-with-iis-smooth-streaming
Hope this helps;-)

**Comment by idseefeld** [comment]
Another _maybe usefull_ link: https://docs.microsoft.com/en-us/iis/media/live-smooth-streaming/apple-http-live-streaming-with-iis-media-services

**Comment by idseefeld** [comment]
... and another solution would be to write a HttpModule which rewrites the url to Azure Storage or even better attached CDN URL. But that is beyond the scope of this extension.
