### ISSUE TITLE
Umbraco package utility no longer works after installing UmbracoFileSystemProviders.Azure

### ISSUE THREAD

**Issue by geoffbentley** [JimBobSquarePants/UmbracoFileSystemProviders.Azure#96]
Hi,

Before installing the UmbracoFileSystemProviders.Azure package, I was able to use the Umbraco Package utility in the back office to bubndle up bits of my site.  Packages were created and downloaded from the local media/created-packages directory.  Since installing UmbracoFileSystemProviders.Azure, the  packages continue to be created in the local/media folder, but when I try to download them, Umbraco is looking for them in the mapped location in Azure blob storage, so the download fails.  I haven't found a way of either pointing the creation path to Azure or alternatively pointing the download path back to the local media directory.  Is this expected behaviour of UmbracoFileSystemProviders.Azure or is it a bug?  Regardless, is there a work around please?
I am using version 7.5.12 of Umbraco and 0.5.10 of UmbracoFileSystemProviders.Azure

Cheers,
Geoff

**Comment by JimBobSquarePants** [comment]
Hi @geoffbentley 

Is all other media working fine?

If so that sounds like an Umbraco bug. There have been issues before where they are not using their own interface. In fact, I'm convinced that, I've actually seen that issue described and that it has been fixed in recent versions. 

I would check their issues tracker and maybe ask in the forums or Twitter.

**Comment by geoffbentley** [comment]
Hi,

Yes the other media all works fine.  I submitted a post on the Umbraco forum about it quite a few weeks ago and haven't had any replies.   I'll check through the issues logs and see what that turns up, but last time I tried I came up with a blank.  I appreciate you replying though.  Thanks very much.

Geoff

**Comment by JimBobSquarePants** [comment]
Always happy to help...

I'll ask on Twitter and see if anyone has any input. I might have a dig through the Umbraco source to see how it works also.

**Comment by geoffbentley** [comment]
That's very good of you.  Thanks very much.

**Comment by geoffbentley** [comment]
I've checked the Umbraco issues tracker.  It seems that the issue has been logged as "U4-10113 - When using a file system provider it does not create a package from the UI", but no one is working on a fix.

**Comment by JimBobSquarePants** [comment]
I knew I'd seen something! I've asked on Twitter, hopefully that will get some action.

**Comment by geoffbentley** [comment]
I'm surprised no one else seems bothered about this.

**Comment by geoffbentley** [comment]
Hi,

As an update on this issue, I have now upgraded to 7.7.6 and this fixed the problem I was getting with the package creation and download..  

Unfortunately however, since the upgrade I can no longer read my media out of blob storage  When I save files they get written to blob storage alright but then Umbraco is reading from its local path.  Are you aware of this issue?

Cheers.

**Comment by JimBobSquarePants** [comment]
@geoffbentley Have you checked you virtual path provider configuration. My money says you the config in your media folder is incorrect.

https://github.com/JimBobSquarePants/UmbracoFileSystemProviders.Azure#virtual-path-provider

**Comment by geoffbentley** [comment]
Spot on!  Thanks very much.

**Comment by JimBobSquarePants** [comment]
Great stuff 😄  I'll close this off then.
