### ISSUE TITLE
Configuration and performance of DiskCache vs AzureBlobCache?

### ISSUE THREAD

**Issue by MichaelNielsenDK** [JimBobSquarePants/UmbracoFileSystemProviders.Azure#97]
I've moved the media archive of a solution to blob storage, and figured it might be beneficial for image requests to not hit the webserver, as it's a high traffic solution. 

So I've tested moving the image cache to blob storage with the AzureBlobCache package. 

It works fine, but I noticed image requests are still hitting the webserver, but gives 302 redirects.

It seems to be slower than just using DiskCache, but I'm not entirely sure. 

I can set StreamCachedImage=true, but that seemed to be even slower, and is also cautioned in the config comment here
http://imageprocessor.org/imageprocessor-web/plugins/azure-blob-cache/#config 
when not using a CDN. 

I wasn't planning on using a CDN, but traffic does come from multiple countries, so it could probably make sense. 

So my question is, what configuration would be best for performance? 

Keep using DiskCache, because that is just the fastest way to serve images?

Use AzureBlobCache without CDN and StreamCachedImage=false, because I shouldn't worry about the 302 redirects, and it's just as fast as DiskCache. 

Use CDN+StreamCachedImage=true, because the benefits of the CDN and image requests not hitting the server is best.

**Comment by JimBobSquarePants** [comment]
Hi @MichaelNielsenDK 

Wrong repo. This should be on the ImageProcessor repo though it's really a question not an issue.

I've migrated it for you.

https://github.com/JimBobSquarePants/ImageProcessor/issues/638
