### ISSUE TITLE
load image file to stream

### ISSUE THREAD

**Issue by james-lau** [JimBobSquarePants/UmbracoFileSystemProviders.Azure#99]
I am using the below function to load image file from stream:

``` c#
public Image GetImage(int id)
{
	Image image = null;
	var ms = new MemoryStream();
	var media = Umbraco.TypedMedia(id);
	if (media != null)
	{
		try
		{
			var path = Server.MapPath(media.Url);
			if (System.IO.File.Exists(path))
			{
				using (Stream input = System.IO.File.OpenRead(path))
				{
					input.CopyTo(ms);
					ms.Position = 0;

					image = Image.FromStream(ms);            
				}
			}
		}
		catch { }
	}
	return image;
}
```

After deploy the  web site to Azure and move the media folder to blob, the function not working anymore. 

How can I detect the web site using UmbracoFileSystemProviders.Azure, and properly load a blob to memory stream.

Thanks for help.

**Comment by akuryan** [comment]
Maybe this can help: https://our.umbraco.org/forum/developers/extending-umbraco/71422-how-to-get-bytes-of-media-and-mimtype-in-umbraco-7-backoffice

**Comment by james-lau** [comment]
It works! thank you.
